#!/usr/bin/env python3
"""Regenerate theme/_fonts-embedded.scss from the .woff2 files in theme/fonts/.

Run from the theme/ directory:  python3 build_fonts.py

The fonts are inlined as base64 so that a rendered deck is a single file that
works offline, over email, and on GitHub Pages with no external requests.
Only re-run this if you add or replace a font file.
"""
import base64
import pathlib

THAI = "U+0E01-0E5B, U+200C-200D, U+25CC"

SPECS = [
    ("Source Serif 4",   "normal", 400, "source-serif-4-latin-400-normal.woff2", None),
    ("Source Serif 4",   "italic", 400, "source-serif-4-latin-400-italic.woff2", None),
    ("Source Serif 4",   "normal", 600, "source-serif-4-latin-600-normal.woff2", None),
    ("Source Serif 4",   "normal", 700, "source-serif-4-latin-700-normal.woff2", None),
    ("Source Sans 3",    "normal", 400, "source-sans-3-latin-400-normal.woff2",  None),
    ("Source Sans 3",    "italic", 400, "source-sans-3-latin-400-italic.woff2",  None),
    ("Source Sans 3",    "normal", 600, "source-sans-3-latin-600-normal.woff2",  None),
    ("Source Sans 3",    "normal", 700, "source-sans-3-latin-700-normal.woff2",  None),
    ("Sarabun",          "normal", 400, "sarabun-thai-400-normal.woff2",         THAI),
    ("Sarabun",          "normal", 600, "sarabun-thai-600-normal.woff2",         THAI),
    ("Sarabun",          "normal", 700, "sarabun-thai-700-normal.woff2",         THAI),
    ("Noto Serif Thai",  "normal", 400, "noto-serif-thai-thai-400-normal.woff2", THAI),
    ("Noto Serif Thai",  "normal", 700, "noto-serif-thai-thai-700-normal.woff2", THAI),
]


def main() -> None:
    fonts = pathlib.Path("fonts")
    out = [
        "/* Auto-generated by theme/build_fonts.py — do not edit by hand.",
        "   Fonts are inlined so a deck renders identically offline, in email,",
        "   and on GitHub Pages, with no external requests. */",
        "",
    ]
    for family, style, weight, filename, unicode_range in SPECS:
        b64 = base64.b64encode((fonts / filename).read_bytes()).decode()
        ur = f"\n  unicode-range:{unicode_range};" if unicode_range else ""
        out.append(
            f'@font-face {{ font-family:"{family}"; font-style:{style}; font-weight:{weight};\n'
            f'  src:url(data:font/woff2;base64,{b64}) format("woff2");{ur}\n'
            f"  font-display:swap; }}"
        )
    target = pathlib.Path("_fonts-embedded.scss")
    target.write_text("\n".join(out) + "\n")
    print(f"wrote {target} ({target.stat().st_size // 1024} KB)")


if __name__ == "__main__":
    main()
