<!DOCTYPE html>
<html lang="en"><head>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-html/tabby.min.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-d4d76bf8491c20bad77d141916dc28e1.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.43">

  <meta name="author" content="Soorathep Kheawhom">
  <meta name="dcterms.date" content="2026-08-17">
  <title>2105623 – Modeling I: linear models, product mix, multiperiod planning and inventory</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="site_libs/revealjs/dist/theme/quarto-adebb5cf30333392721641149eb81241.css">
  <link href="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-color="#1C242B" class="quarto-title-block center">
  <h1 class="title">Modeling I: linear models, product mix, multiperiod planning and inventory</h1>
  <p class="subtitle">Week 2 · 2105623 Optimization of Chemical Processes</p>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Soorathep Kheawhom 
</div>
</div>
</div>

  <p class="date">17 August 2026</p>
</section>
<section id="three-hours-nine-blocks" class="slide level2 tint" data-background-color="#F3F0EB">
<h2>Three hours, nine blocks</h2>
<div class="kicker c-amber">
<p>Today</p>
</div>
<div class="agenda">
<ul>
<li><span class="chip c-slate">5 min</span> Recap of Week 1, and one pitch card worth showing the room</li>
<li><span class="chip c-teal">35 min</span> Block 1: the structured specification, and the four reusable patterns</li>
<li><span class="chip c-amber">15 min</span> Activity 1 — from words to symbols</li>
<li><span class="chip c-mist">10 min</span> Break</li>
<li><span class="chip c-teal">40 min</span> Block 2: time-indexed formulation, inventory balance, backlog, capacity</li>
<li><span class="chip c-amber">15 min</span> Activity 2 — build it and predict it</li>
<li><span class="chip c-mist">10 min</span> Break</li>
<li><span class="chip c-teal">45 min</span> Block 3: multi-product and shared capacity, the value of look-ahead, where the spreadsheet stops</li>
<li><span class="chip c-slate">5 min</span> Wrap-up, and HW1 is released</li>
</ul>
</div>
<div class="foot">
<div class="note">
<p>Lecture 120 minutes, activities 30, breaks 20, administration 10. Tool of the week: <strong>OpenSolver</strong>, because periods laid across columns read naturally in a spreadsheet.</p>
</div>
</div>
</section>
<section id="by-three-oclock-you-should-be-able-to" class="slide level2 tint" data-background-color="#F3F0EB">
<h2>By three o’clock you should be able to</h2>
<div class="kicker c-teal">
<p>Learning objectives · CLO 1 and CLO 4</p>
</div>
<div class="cards g3">
<div class="card c-teal">
<p><span class="dot"></span></p>
<h3 id="write-a-specification">Write a specification</h3>
<p>A unit on every symbol, bounds on every variable — and find the ambiguities in somebody else’s.</p>
</div>
<div class="card c-amber">
<p><span class="dot"></span></p>
<h3 id="name-the-four-patterns">Name the four patterns</h3>
<p>Index set, balance equation, capacity constraint, linking constraint, and apply each one.</p>
</div>
<div class="card c-sky">
<p><span class="dot"></span></p>
<h3 id="index-over-a-horizon">Index over a horizon</h3>
<p>Write an inventory balance linking consecutive periods, and state your start-versus-end convention.</p>
</div>
<div class="card c-sage">
<p><span class="dot"></span></p>
<h3 id="price-a-backlog">Price a backlog</h3>
<p>Separately from held stock, without a binary variable, and say why a horizon-end condition is mandatory.</p>
</div>
<div class="card c-rust">
<p><span class="dot"></span></p>
<h3 id="build-it-in-opensolver">Build it in OpenSolver</h3>
<p>Map every spreadsheet range to its algebraic symbol, and reproduce a stated optimum.</p>
</div>
<div class="card c-plum">
<p><span class="dot"></span></p>
<h3 id="read-a-capacity-dual">Read a capacity dual</h3>
<p>Period by period, and use it to justify where a debottlenecking budget goes.</p>
</div>
</div>
</section>
<section id="where-weeks-2-to-5-live" class="slide level2">
<h2>Where Weeks 2 to 5 live</h2>
<div class="kicker c-amber">
<p>Recap of Week 1</p>
</div>
<div class="steps">
<div class="step c-mist">
<p><span class="n">1</span><span class="h">Verbal</span><span class="d">the problem in prose</span></p>
</div>
<div class="step c-amber">
<p><span class="n">2</span><span class="h">Specification</span><span class="d"><strong>we are here</strong></span></p>
</div>
<div class="step c-amber">
<p><span class="n">3</span><span class="h">Algebra</span><span class="d"><strong>and here</strong></span></p>
</div>
<div class="step c-mist">
<p><span class="n">4</span><span class="h">Code</span><span class="d">Weeks 7 and 8</span></p>
</div>
<div class="step c-mist">
<p><span class="n">5</span><span class="h">Interpretation</span><span class="d">Weeks 7 and 8</span></p>
</div>
</div>
<div class="columns">
<div class="column" style="width:49%;">
<div class="cards">
<div class="card c-teal">
<p><strong>Week 1 established</strong></p>
<p>The four parts of any problem, the standard form, the classification table, the tool stack, and one solved LP: x* = (6, 3) t/week at z* = <strong>3,300.00</strong> USD/week with two binding resources.</p>
</div>
</div>
</div><div class="column" style="width:49%;">
<div class="cards">
<div class="card c-slate">
<p><strong>And the geometry</strong></p>
<p>An LP with a finite optimum has an optimal vertex. <strong>That argument is not repeated today.</strong> Every model in this session is an LP and the same picture applies, unchanged.</p>
</div>
</div>
</div></div>
<div class="foot">
<div class="punch">
<p>The modeling block is stages 2 and 3, done four times on four kinds of structure. Weeks 2 to 5 add no new mathematics at all.</p>
</div>
</div>
</section>
<section id="the-specification-and-the-four-patterns" class="slide level2 dark divider c-teal" data-background-color="#1C242B">
<h2>The specification, and the four patterns</h2>
<div class="kicker">
<p>Lecture block 1 · 35 minutes</p>
</div>
<div class="lede">
<p>One document, four patterns,<br> and one small model in which all four are visible at once.</p>
</div>
</section>
<section id="stage-2-is-the-real-deliverable-of-engineering-thinking" class="slide level2">
<h2>Stage 2 is the real deliverable of engineering thinking</h2>
<div class="kicker c-teal">
<p>Why a document, and not algebra</p>
</div>
<div class="columns">
<div class="column" style="width:52%;">
<div class="numbered n4">
<ol type="1">
<li><strong>Index sets</strong> Each one named, with its membership stated.</li>
<li><strong>Parameters</strong> Symbol, meaning, unit, and the source of the number.</li>
<li><strong>Decision variables</strong> Symbol, unit, and bounds.</li>
<li><strong>One objective</strong> Stated in words, with its unit.</li>
<li><strong>Restrictions</strong> Numbered, in words, including the ones you assume away.</li>
</ol>
</div>
</div><div class="column" style="width:46%;">
<div class="cards">
<div class="card c-rust">
<p><strong>Why this and not algebra</strong></p>
<p>Algebra hides assumptions. The symbol <em>I</em><sub><em>t</em></sub> looks precise, but it does not say whether inventory is measured at the start or the end of the period. The specification has to say so <strong>in words</strong>, where a reader can disagree with it.</p>
</div>
</div>
<div class="punch">
<p>A specification that requires guessing will be guessed at, and the guess will be plausible, silent and unlabeled.</p>
</div>
<div class="note">
<p>The code is a <em>translation</em> of this document. If the specification is right, writing the algebra and then the model file is close to mechanical.</p>
</div>
</div></div>
</section>
<section id="the-specification-template-blank" class="slide level2 tint" data-background-color="#F3F0EB">
<h2>The specification template, blank</h2>
<div class="kicker c-amber">
<p>This is what Activity 1 asks you to fill in</p>
</div>
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Section</th>
<th>What goes in it</th>
<th>The question it forces you to answer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Sets and indices</strong></td>
<td>every dimension of the problem, named, with its membership</td>
<td>What is repeated, and over what?</td>
</tr>
<tr class="even">
<td><strong>Parameters</strong></td>
<td>symbol, meaning, <strong>unit</strong>, source of the number</td>
<td>Which numbers are fixed before the model is solved, and who owns them?</td>
</tr>
<tr class="odd">
<td><strong>Decision variables</strong></td>
<td>symbol with full index, <strong>unit</strong>, <strong>bounds</strong></td>
<td>What is genuinely under your control?</td>
</tr>
<tr class="even">
<td><strong>Objective</strong></td>
<td>one sentence in words, with its <strong>unit</strong></td>
<td>What counts as better, in what currency, over what period?</td>
</tr>
<tr class="odd">
<td><strong>Constraints</strong></td>
<td>numbered, in words</td>
<td>What must hold, and is each one hard or soft?</td>
</tr>
<tr class="even">
<td><strong>Assumptions</strong></td>
<td>numbered alongside the constraints</td>
<td>What did you decide to ignore, and would a reviewer accept it?</td>
</tr>
</tbody>
</table>
<div class="foot">
<div class="flag">
<p>Assumptions are written as numbered restrictions, not as prose. “Everything produced is sold” is a modeling decision with a cost attached, and numbering it is what lets somebody challenge it.</p>
</div>
</div>
</section>
<section id="parameters-carry-a-unit-and-a-source" class="slide level2">
<h2>Parameters carry a unit and a source</h2>
<div class="kicker c-teal">
<p>Specification, row 2</p>
</div>
<table class="caption-top">
<colgroup>
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Symbol</th>
<th>Meaning</th>
<th>Unit</th>
<th>Where the number comes from</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>d</em><sub><em>t</em></sub></td>
<td>demand in period <em>t</em></td>
<td>t/month</td>
<td>sales forecast, revision date recorded</td>
</tr>
<tr class="even">
<td><em>C</em><sub><em>t</em></sub></td>
<td>production capacity</td>
<td>t/month</td>
<td>line rate times available hours</td>
</tr>
<tr class="odd">
<td><em>c</em><sub><em>t</em></sub></td>
<td>unit production cost</td>
<td>USD/t</td>
<td>standard cost plus the electricity contract</td>
</tr>
<tr class="even">
<td><em>h</em></td>
<td>inventory holding cost</td>
<td>USD/t/month</td>
<td>working capital plus storage</td>
</tr>
<tr class="odd">
<td><em>b</em></td>
<td>backlog penalty</td>
<td>USD/t/month</td>
<td>expedited freight plus contractual damages</td>
</tr>
<tr class="even">
<td><em>I</em><sub>0</sub></td>
<td>opening inventory</td>
<td>t</td>
<td>the stock ledger at the planning date</td>
</tr>
<tr class="odd">
<td><em>ρ</em><sub><em>p</em></sub></td>
<td>reactor hours per tonne of <em>p</em></td>
<td>h/t</td>
<td>the process, measured and not assumed</td>
</tr>
</tbody>
</table>
<div class="columns">
<div class="column" style="width:49%;">
<div class="note">
<p>A parameter is anything fixed <strong>before</strong> the problem is solved. If you can change it, it is a variable; if you cannot, it is a parameter. Confusing the two is the commonest stage-2 error.</p>
</div>
</div><div class="column" style="width:49%;">
<div class="flag">
<p><em>h</em> and <em>b</em> carry <strong>per month</strong> in their unit. That is what makes a backlog charged <em>again</em> in every period until it is cleared — and it is exactly the modeling decision that drives the answer at half past two.</p>
</div>
</div></div>
</section>
<section id="decision-variables-carry-a-unit-and-bounds" class="slide level2">
<h2>Decision variables carry a unit and bounds</h2>
<div class="kicker c-amber">
<p>Specification, row 3</p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<div class="numbered n3">
<ol type="1">
<li><strong>A symbol with its full index</strong> <em>x</em><sub><em>p</em>,<em>t</em></sub>, not <em>x</em>.</li>
<li><strong>A unit</strong> Tonnes per month is not tonnes.</li>
<li><strong>Bounds</strong> At minimum: is it non-negative? Is it bounded above by something physical?</li>
</ol>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th>Symbol</th>
<th>Meaning</th>
<th>Unit</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>x</em><sub><em>t</em></sub> ≥ 0</td>
<td>production in period <em>t</em></td>
<td>t</td>
</tr>
<tr class="even">
<td><em>I</em><sub><em>t</em></sub> ≥ 0</td>
<td>inventory carried out of <em>t</em></td>
<td>t</td>
</tr>
<tr class="odd">
<td><em>B</em><sub><em>t</em></sub> ≥ 0</td>
<td>backlog carried out of <em>t</em></td>
<td>t</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:48%;">
<div class="cards">
<div class="card c-rust">
<p><strong>Bounds are free performance and free safety</strong></p>
<p>An unbounded variable is the commonest cause of an unbounded model, and an unbounded integer variable will cripple a solver’s presolve in Week 11. Write the physical bound even when you believe the constraints already imply it. It costs one line and it documents the physics.</p>
</div>
<div class="card c-teal">
<p><strong>A variable is not a formula</strong></p>
<p><em>I</em><sub><em>t</em></sub> is a <strong>variable</strong> that the balance equation ties to production and demand. Do not write it as an expression. Keeping it a variable is what lets you bound it, price it, and read its dual.</p>
</div>
</div>
</div></div>
</section>
<section id="units-on-every-symbol-the-cheapest-error-detector-there-is" class="slide level2">
<h2>Units on every symbol: the cheapest error detector there is</h2>
<div class="kicker c-teal">
<p>Thirty seconds, every time</p>
</div>
<div class="spec">
<p><span class="eyebrow">The check, applied to the inventory balance</span></p>
<p><em>I</em><sub><em>t</em>−1</sub> [t] &nbsp; − &nbsp; <em>B</em><sub><em>t</em>−1</sub> [t] &nbsp; + &nbsp; <em>x</em><sub><em>t</em></sub> [t] &nbsp; − &nbsp; <em>d</em><sub><em>t</em></sub> [t] &nbsp; = &nbsp; <em>I</em><sub><em>t</em></sub> [t] &nbsp; − &nbsp; <em>B</em><sub><em>t</em></sub> [t]</p>
<p>Every term is a tonnage. If any one of them had carried a <strong>rate</strong>, the equation would be wrong, and it would still solve.</p>
</div>
<div class="columns">
<div class="column" style="width:49%;">
<div class="cards">
<div class="card c-teal">
<p><span class="eyebrow">And to the objective</span></p>
<p><em>c</em><sub><em>t</em></sub> [USD/t] · <em>x</em><sub><em>t</em></sub> [t] &nbsp; + &nbsp; <em>h</em> [USD/t/month] · <em>I</em><sub><em>t</em></sub> [t] · 1 [month] &nbsp; ⇒ &nbsp; [USD]</p>
<p>The “one period” in the holding term is implicit. Writing it out is what stops you putting a weekly rate into a monthly model.</p>
</div>
</div>
</div><div class="column" style="width:49%;">
<div class="cards">
<div class="card c-rust">
<p><span class="eyebrow">The class of error units catch</span></p>
<p>Mixing a <strong>stock</strong> (tonnes) with a <strong>flow</strong> (tonnes per month), or mixing two time bases. Neither produces an error message. Both produce a plan that is confidently wrong by a factor of four or five.</p>
</div>
</div>
</div></div>
</section>
<section id="pattern-1-the-index-set" class="slide level2">
<h2>Pattern 1 · the index set</h2>
<div class="kicker c-amber">
<p>The same relation repeated over a family</p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<div class="spec">
<p><span class="eyebrow">Template</span></p>
<p><em>i</em> ∈ <em>I</em> &nbsp;&nbsp;&nbsp; and then &nbsp;&nbsp;&nbsp; <em>x</em><sub><em>i</em></sub> &nbsp;⟶&nbsp; <em>x</em><sub><em>i</em>,<em>t</em></sub></p>
</div>
<div class="dots">
<ul>
<li><strong>Name every dimension once</strong> Then index parameters, variables and constraints over it, and write the relation once. The solver expands it.</li>
<li><strong>Growth becomes a data change</strong> Adding a product, a period or a site changes the data, not the model. The number of rows grows; the number of ideas does not.</li>
<li><strong>Where it reappears</strong> Every week of this course. It is the reason the Pyomo Set component exists at all.</li>
</ul>
</div>
</div><div class="column" style="width:48%;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Dimension</th>
<th>Index</th>
<th>Set</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>product or grade</td>
<td><em>p</em></td>
<td><em>P</em></td>
</tr>
<tr class="even">
<td>resource or operation</td>
<td><em>r</em>, <em>s</em></td>
<td><em>R</em>, <em>S</em></td>
</tr>
<tr class="odd">
<td>period</td>
<td><em>t</em></td>
<td><em>T</em>, <strong>ordered</strong></td>
</tr>
<tr class="even">
<td>node or site</td>
<td><em>i</em>, <em>j</em></td>
<td><em>N</em></td>
</tr>
<tr class="odd">
<td>scenario</td>
<td><em>ω</em></td>
<td><em>Ω</em></td>
</tr>
</tbody>
</table>
<div class="cards">
<div class="card c-rust">
<p><strong>Ordered sets matter</strong></p>
<p>A time set must be <strong>ordered</strong>, because the model needs to know what <em>t</em> − 1 means. In Pyomo, <code>pyo.Set(initialize=T, ordered=True)</code>, then <code>m.T.prev(t)</code>. In a spreadsheet, “the column immediately to the left” is the same statement — and it is why periods run across columns.</p>
</div>
</div>
</div></div>
</section>
<section id="pattern-2-the-balance-equation" class="slide level2">
<h2>Pattern 2 · the balance equation</h2>
<div class="kicker c-teal">
<p>What goes in equals what goes out plus what accumulates</p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<div class="spec">
<p><span class="eyebrow">Template</span></p>
<p>accumulation &nbsp;=&nbsp; inflow &nbsp;−&nbsp; outflow</p>
<p><em>I</em><sub><em>t</em>−1</sub> &nbsp;+&nbsp; <em>x</em><sub><em>t</em></sub> &nbsp;−&nbsp; <em>d</em><sub><em>t</em></sub> &nbsp;=&nbsp; <em>I</em><sub><em>t</em></sub></p>
</div>
<div class="dots">
<ul>
<li><strong>It is the same law as a material balance</strong> Only the boundary moves. Draw it around a vessel and it is a mass balance; draw it around a period and it is an inventory balance.</li>
<li><strong>It is an equality</strong> And it is the backbone of the model, not a refinement of it.</li>
<li><strong>Where it reappears</strong> As the node balance in Week 3, as a component balance in Week 4, and as a unit balance in both.</li>
</ul>
</div>
</div><div class="column" style="width:48%;">
<div class="cards">
<div class="card c-rust">
<p><strong>The most expensive class of error</strong></p>
<p>A <strong>missing</strong> balance is worse than a wrong one. The model still solves. It still reports a plan. It has simply stopped conserving material, and nothing on the screen says so.</p>
</div>
<div class="card c-teal">
<p><strong>Patterns 1 and 2 together</strong></p>
<p>Written once, expanded over the ordered set <em>T</em>. One line of specification becomes six rows in the spreadsheet, and the six rows are what make it a plan rather than six unrelated decisions.</p>
</div>
</div>
</div></div>
</section>
<section id="pattern-3-the-capacity-constraint" class="slide level2">
<h2>Pattern 3 · the capacity constraint</h2>
<div class="kicker c-amber">
<p>A shared resource limits a sum</p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<div class="spec">
<p><span class="eyebrow">Template</span></p>
<p>Σ<sub><em>i</em></sub> <em>a</em><sub><em>ri</em></sub> <em>x</em><sub><em>i</em></sub> &nbsp; ≤ &nbsp; <em>b</em><sub><em>r</em></sub> &nbsp;&nbsp; for every <em>r</em> ∈ <em>R</em></p>
</div>
<div class="dots">
<ul>
<li><strong>One inequality per resource</strong> And one per resource per period as well, if the resource is renewed each period.</li>
<li><strong>The sum is what makes it a constraint</strong> If only one activity used the resource, it would be a bound on a single variable and the solver would handle it for free.</li>
<li><strong>Where it reappears</strong> Arc capacity in Week 3, pool capacity in Week 4, unit capacity in Week 5.</li>
</ul>
</div>
</div><div class="column" style="width:48%;">
<div class="cards">
<div class="card c-teal">
<p><strong>Renewable, or consumed once</strong></p>
<p><em>x</em><sub><em>t</em></sub> ≤ <em>C</em><sub><em>t</em></sub> for every <em>t</em> &nbsp;&nbsp; versus &nbsp;&nbsp; Σ<sub><em>t</em></sub> <em>x</em><sub><em>t</em></sub> ≤ <em>C</em></p>
<p>Line hours that reset every month give one inequality <strong>per period</strong>. A fixed allocation of catalyst consumed once over the horizon gives <strong>one</strong> inequality summed over <em>t</em>.</p>
</div>
</div>
<div class="punch">
<p>They behave completely differently, and nothing in the English of a problem statement tells you which is meant. The specification has to say.</p>
</div>
</div></div>
</section>
<section id="pattern-4-the-linking-constraint" class="slide level2">
<h2>Pattern 4 · the linking constraint</h2>
<div class="kicker c-teal">
<p>A variable in one block constrains another</p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<div class="spec">
<p><span class="eyebrow">Template</span></p>
<p>any constraint whose index<br>spans <strong>more than one block</strong></p>
</div>
<div class="dots">
<ul>
<li><strong>It destroys separability</strong> Which sounds like a defect and is in fact the whole point. If the blocks separated, you would not need a solver — you would need arithmetic.</li>
<li><strong>That is where the value of optimizing lives</strong> Every dollar a planning model earns comes through a linking constraint.</li>
<li><strong>Where it reappears</strong> Transshipment nodes in Week 3, pooling in Week 4, big-M links in Week 5.</li>
</ul>
</div>
</div><div class="column" style="width:48%;">
<div class="cards">
<div class="card c-amber">
<p><span class="eyebrow">Temporal linking · block 2</span></p>
<p>The inventory balance carries stock from <em>t</em> − 1 into <em>t</em>, so the periods <strong>cannot be planned one at a time</strong>.</p>
</div>
<div class="card c-rust">
<p><span class="eyebrow">Resource linking · block 3</span></p>
<p>One shared reactor is used by both products, so the products <strong>cannot be planned one at a time</strong>.</p>
</div>
</div>
<div class="punch">
<p>Remove both and the model falls apart into a stack of independent one-period problems that nobody needs a solver for.</p>
</div>
</div></div>
</section>
<section id="the-same-four-patterns-in-four-unrelated-domains" class="slide level2 tint" data-background-color="#F3F0EB">
<h2>The same four patterns in four unrelated domains</h2>
<div class="kicker c-amber">
<p>Why they are worth naming</p>
</div>
<table class="caption-top">
<colgroup>
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>1 Index set</th>
<th>2 Balance</th>
<th>3 Capacity</th>
<th>4 Linking</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Refinery blend</strong></td>
<td>feedstocks <em>c</em>, properties <em>q</em></td>
<td>volume balance: blend = Σ components</td>
<td>feedstock availability, over <em>c</em></td>
<td>quality specs, over <em>q</em></td>
</tr>
<tr class="even">
<td><strong>Staff roster</strong></td>
<td>staff <em>e</em>, shifts <em>t</em></td>
<td><em>only if</em> headcount carries across periods</td>
<td>cover per shift; hours per person</td>
<td>rest rules, over consecutive <em>t</em></td>
</tr>
<tr class="odd">
<td><strong>Battery dispatch</strong></td>
<td>hours <em>t</em>, |<em>T</em>| = 24</td>
<td>state-of-charge balance, over <em>t</em></td>
<td>power limit and energy capacity per <em>t</em></td>
<td>the state-of-charge balance itself</td>
</tr>
<tr class="even">
<td><strong>Warehouse network</strong></td>
<td>plants <em>i</em>, warehouses <em>j</em>, customers <em>k</em></td>
<td>node balance at each warehouse</td>
<td>plant supply; warehouse throughput</td>
<td>the warehouse node balance</td>
</tr>
</tbody>
</table>
<div class="foot">
<div class="note">
<p><strong>The honest nuance.</strong> The roster’s balance row is arguable. If staff are simply assigned to shifts, the cover requirement is a capacity constraint with a ≥ sense and there is no balance at all. A balance appears only if a pool of people is carried across periods. Both readings are defensible — and the specification is where you say which one you chose.</p>
</div>
</div>
</section>
<section id="the-warm-up-stages-1-to-3-the-finishing-shop" class="slide level2">
<h2>The warm-up, stages 1 to 3 · the finishing shop</h2>
<div class="kicker c-teal">
<p>All four patterns, in a model small enough to hold in the head</p>
</div>
<p>A finishing shop attached to the electrolyte plant packages two grades for zinc-air cell assembly, a <strong>Standard</strong> grade and a <strong>HighPurity</strong> grade. Both pass through the same three operations in order: mixing, ion-exchange purification, and filling. The three operations have different weekly hour allocations because they are shared with other campaigns. HighPurity is worth more per tonne but spends four times as long in purification. Everything finished is sold.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th>Operation</th>
<th>Standard, h/t</th>
<th>HighPurity, h/t</th>
<th>Available, h/week</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mixing</td>
<td>2</td>
<td>3</td>
<td>120</td>
</tr>
<tr class="even">
<td>Ion-exchange purification</td>
<td>1</td>
<td>4</td>
<td>104</td>
</tr>
<tr class="odd">
<td>Filling</td>
<td>1</td>
<td>1</td>
<td>44</td>
</tr>
<tr class="even">
<td><strong>Contribution margin, USD/t</strong></td>
<td><strong>520</strong></td>
<td><strong>790</strong></td>
<td></td>
</tr>
</tbody>
</table>
<div class="foot">
<div class="note">
<p><strong>Stage 2, restrictions in words.</strong> R1. On each operation, the hours consumed cannot exceed the hours allocated. R2. Production cannot be negative. R3. There is no demand limit, because everything finished is sold — <em>and R3 is an assumption, numbered so that it can be challenged.</em> &nbsp; <strong>Stage 3.</strong> max Σ<sub><em>p</em></sub> <em>c</em><sub><em>p</em></sub> <em>x</em><sub><em>p</em></sub> subject to Σ<sub><em>p</em></sub> <em>a</em><sub><em>sp</em></sub> <em>x</em><sub><em>p</em></sub> ≤ <em>b</em><sub><em>s</em></sub> for every <em>s</em>, with <em>x</em><sub><em>p</em></sub> ≥ 0 and [h/t]·[t/week] = [h/week] on every row.</p>
</div>
</div>
</section>
<section id="the-warm-up-stages-4-and-5-the-answer-and-what-it-says" class="slide level2">
<h2>The warm-up, stages 4 and 5 · the answer and what it says</h2>
<div class="kicker c-amber">
<p>Busiest and binding are different words</p>
</div>
<div class="columns">
<div class="column" style="width:52%;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Operation</th>
<th>Used, h</th>
<th>Avail., h</th>
<th>Slack, h</th>
<th>Dual, USD/h</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mixing</td>
<td>108</td>
<td>120</td>
<td>12</td>
<td><strong>0</strong></td>
</tr>
<tr class="even">
<td>Purification</td>
<td>104</td>
<td>104</td>
<td>0</td>
<td><strong>90</strong></td>
</tr>
<tr class="odd">
<td>Filling</td>
<td>44</td>
<td>44</td>
<td>0</td>
<td><strong>430</strong></td>
</tr>
</tbody>
</table>
<div class="cards">
<div class="card c-teal">
<p><strong>The answer</strong></p>
<p><strong>24 t of Standard and 20 t of HighPurity</strong>, for <strong>28,280.00 USD</strong> of contribution margin in the week.</p>
<p>Verified two ways in the notebook: vertex enumeration in NumPy, and a finite-difference check on every dual.</p>
</div>
</div>
</div><div class="column" style="width:46%;">
<div class="cards">
<div class="card c-rust">
<p><strong>The engineering reading</strong></p>
<p>Buy an overtime shift on <strong>filling</strong> first, not on the operation that looks busiest.</p>
<p>Mixing consumes 108 hours, more than either other operation in absolute terms, and it is worth <strong>exactly zero</strong> at the margin.</p>
</div>
<div class="card c-slate">
<p><strong>And the limitation we spend the rest of the day removing</strong></p>
<p>This plans one week in isolation. It has no memory. It cannot build stock now for a peak later, and it cannot say that a shortfall this week must be delivered next week.</p>
</div>
</div>
</div></div>
</section>
<section id="from-words-to-symbols" class="slide level2 dark divider c-amber" data-background-color="#1C242B">
<h2>From words to symbols</h2>
<div class="kicker">
<p>Activity 1 · 15 minutes · pairs, paper</p>
</div>
<div class="lede">
<p>You may not write a single equation<br>for the next eight minutes. Not one.</p>
</div>
<div class="flag">
<p>Write what the symbols mean, what units they carry, and what the constraints say in English.</p>
</div>
</section>
<section id="aurora-specialty-chemicals" class="slide level2">
<h2>Aurora Specialty Chemicals</h2>
<div class="kicker c-amber">
<p>Activity 1 · 15 minutes · pairs, paper</p>
</div>
<div class="lede">
<p>Aurora Specialty Chemicals makes two grades of electrolyte, <strong>Standard</strong> and <strong>HighPurity</strong>, on one shared reactor train. The reactor is available <strong>640 hours per month</strong>. Standard needs <strong>1.0</strong> reactor hours per tonne and HighPurity needs <strong>1.4</strong>. Marketing has issued a demand forecast for the next four months: for Standard, <strong>180, 210, 260 and 190</strong> tonnes; for HighPurity, <strong>90, 120, 150 and 110</strong> tonnes. Production cost differs by grade and rises in month 3, when electricity is dearest. Anything finished but not shipped in the month it is made is stored in a single warehouse that holds <strong>120 tonnes</strong>, at <strong>7 USD per tonne per month</strong>. Thirty tonnes of Standard are already in store. The plant wants the cheapest four-month plan that meets the forecast.</p>
</div>
<div class="columns">
<div class="column" style="width:52%;">
<div class="cards">
<div class="card c-amber">
<p><strong>Write only the specification table</strong></p>
<p>Sets and indices · parameters with symbol and units · decision variables with symbol, units and bounds · the objective in words with its units · the constraints in words.</p>
<p><strong>Writing algebra is forbidden. So is writing any spreadsheet formula.</strong></p>
</div>
</div>
</div><div class="column" style="width:46%;">
<div class="numbered n3">
<ol type="1">
<li><strong>0 to 8 min · pairs</strong> Write the specification table.</li>
<li><strong>8 to 13 min · swapped</strong> Find one ambiguity in the sheet of the pair beside you, and circle it.</li>
<li><strong>13 to 15 min · plenary</strong> Two pairs read theirs out.</li>
</ol>
</div>
</div></div>
</section>
<section id="section" class="slide level2 dark break c-teal" data-background-color="#1C242B">
<h2>&nbsp;</h2>
<div class="vcenter">
<div class="break-circle">
<p><span>10</span></p>
</div>
<div class="big-label">
<p>minute break</p>
</div>
<div class="note">
<p>Then: what a time index does to a model, the inventory balance and its start-versus-end convention, backlog priced separately from held stock, and the whole six-period model assembled one family at a time</p>
</div>
</div>
</section>
<section id="the-time-indexed-formulation" class="slide level2 dark divider c-amber" data-background-color="#1C242B">
<h2>The time-indexed formulation</h2>
<div class="kicker">
<p>Lecture block 2 · 40 minutes</p>
</div>
<div class="lede">
<p>One index, added to every variable,<br> turns a decision into a plan.</p>
</div>
</section>
<section id="a-time-index-turns-one-decision-into-a-plan" class="slide level2">
<h2>A time index turns one decision into a plan</h2>
<div class="kicker c-teal">
<p>Pattern 4, drawn</p>
</div>
<svg viewbox="0 0 900 250" style="width:100%;max-width:980px" role="img" aria-label="Six period boxes labelled t equals 1 through 6 in a row, joined left to right by amber arrows carrying inventory and backlog from each period into the next, with a production arrow entering each box from above and a demand arrow leaving each box below.">
<g fill="#F3F0EB" stroke="#0F6E6B" stroke-width="2.5"><rect x="40" y="100" width="100" height="56" rx="5"></rect><rect x="185" y="100" width="100" height="56" rx="5"></rect><rect x="330" y="100" width="100" height="56" rx="5"></rect><rect x="475" y="100" width="100" height="56" rx="5"></rect><rect x="620" y="100" width="100" height="56" rx="5"></rect><rect x="765" y="100" width="100" height="56" rx="5"></rect></g> <g font-size="18" fill="#1C242B" text-anchor="middle"><text x="90" y="134">t = 1</text><text x="235" y="134">t = 2</text><text x="380" y="134">t = 3</text><text x="525" y="134">t = 4</text><text x="670" y="134">t = 5</text><text x="815" y="134">t = 6</text></g> <g stroke="#E29A2D" stroke-width="3"><line x1="143" y1="128" x2="177" y2="128"></line><line x1="288" y1="128" x2="322" y2="128"></line><line x1="433" y1="128" x2="467" y2="128"></line><line x1="578" y1="128" x2="612" y2="128"></line><line x1="723" y1="128" x2="757" y2="128"></line></g> <g fill="#E29A2D"><polygon points="185,128 171,121 171,135"></polygon><polygon points="330,128 316,121 316,135"></polygon><polygon points="475,128 461,121 461,135"></polygon><polygon points="620,128 606,121 606,135"></polygon><polygon points="765,128 751,121 751,135"></polygon></g> <g font-size="14" fill="#E29A2D" text-anchor="middle"><text x="162" y="92">Iₜ, Bₜ</text><text x="307" y="92">Iₜ, Bₜ</text><text x="452" y="92">Iₜ, Bₜ</text><text x="597" y="92">Iₜ, Bₜ</text><text x="742" y="92">Iₜ, Bₜ</text></g> <g stroke="#0F6E6B" stroke-width="2.2"><line x1="90" y1="56" x2="90" y2="94"></line><line x1="235" y1="56" x2="235" y2="94"></line><line x1="380" y1="56" x2="380" y2="94"></line><line x1="525" y1="56" x2="525" y2="94"></line><line x1="670" y1="56" x2="670" y2="94"></line><line x1="815" y1="56" x2="815" y2="94"></line></g> <g fill="#0F6E6B"><polygon points="90,100 83,88 97,88"></polygon><polygon points="235,100 228,88 242,88"></polygon><polygon points="380,100 373,88 387,88"></polygon><polygon points="525,100 518,88 532,88"></polygon><polygon points="670,100 663,88 677,88"></polygon><polygon points="815,100 808,88 822,88"></polygon></g> <g stroke="#BE654C" stroke-width="2.2"><line x1="90" y1="156" x2="90" y2="196"></line><line x1="235" y1="156" x2="235" y2="196"></line><line x1="380" y1="156" x2="380" y2="196"></line><line x1="525" y1="156" x2="525" y2="196"></line><line x1="670" y1="156" x2="670" y2="196"></line><line x1="815" y1="156" x2="815" y2="196"></line></g> <g fill="#BE654C"><polygon points="90,204 83,192 97,192"></polygon><polygon points="235,204 228,192 242,192"></polygon><polygon points="380,204 373,192 387,192"></polygon><polygon points="525,204 518,192 532,192"></polygon><polygon points="670,204 663,192 677,192"></polygon><polygon points="815,204 808,192 822,192"></polygon></g> <text x="14" y="46" font-size="16" fill="#0F6E6B">xₜ produced</text> <text x="14" y="228" font-size="16" fill="#BE654C">dₜ shipped</text> <text x="884" y="46" font-size="15" fill="#333F4A" text-anchor="end">the amber arrows are the only place consecutive periods meet</text> <text x="884" y="228" font-size="15" fill="#333F4A" text-anchor="end">cover them and six independent problems are left</text>
</svg>
<div class="columns">
<div class="column" style="width:49%;">
<div class="note">
<p>Without the amber arrows these are six <strong>independent</strong> problems. Each would be solved on its own, and nothing at all would be gained by solving them together. The optimization would be arithmetic.</p>
</div>
</div><div class="column" style="width:49%;">
<div class="flag">
<p>The amber arrows are the <strong>linking constraint</strong> of pattern 4. Everything a multiperiod model can do about seasonality, a demand spike or a cost profile passes through them.</p>
</div>
</div></div>
</section>
<section id="the-inventory-balance" class="slide level2">
<h2>The inventory balance</h2>
<div class="kicker c-amber">
<p>Pattern 2, with the boundary drawn around a period</p>
</div>
<div class="columns">
<div class="column" style="width:46%;">
<svg viewbox="0 0 520 300" style="width:100%;max-width:560px" role="img" aria-label="A control volume drawn around a single period, with net stock flowing in from the left, production entering from above, demand leaving below, and net stock flowing out to the right.">
<rect x="180" y="110" width="160" height="80" rx="6" fill="#F3F0EB" stroke="#0F6E6B" stroke-width="3"></rect> <text x="260" y="157" font-size="20" fill="#1C242B" text-anchor="middle">period t</text> <line x1="30" y1="150" x2="168" y2="150" stroke="#0F6E6B" stroke-width="2.6"></line> <polygon points="180,150 166,142 166,158" fill="#0F6E6B"></polygon> <text x="98" y="138" font-size="16" fill="#0F6E6B" text-anchor="middle">Iₜ₋₁ − Bₜ₋₁</text> <line x1="340" y1="150" x2="478" y2="150" stroke="#0F6E6B" stroke-width="2.6"></line> <polygon points="490,150 476,142 476,158" fill="#0F6E6B"></polygon> <text x="416" y="138" font-size="16" fill="#0F6E6B" text-anchor="middle">Iₜ − Bₜ</text> <line x1="260" y1="34" x2="260" y2="98" stroke="#E29A2D" stroke-width="2.6"></line> <polygon points="260,110 252,96 268,96" fill="#E29A2D"></polygon> <text x="274" y="66" font-size="16" fill="#E29A2D">xₜ produced</text> <line x1="260" y1="190" x2="260" y2="254" stroke="#BE654C" stroke-width="2.6"></line> <polygon points="260,266 252,252 268,252" fill="#BE654C"></polygon> <text x="274" y="228" font-size="16" fill="#BE654C">dₜ shipped</text> <text x="260" y="292" font-size="15" fill="#66727C" text-anchor="middle">same law, new boundary</text>
</svg>
</div><div class="column" style="width:52%;">
<div class="spec">
<p><span class="eyebrow">Accumulation equals inflow minus outflow, around a period</span></p>
<p><em>I</em><sub><em>t</em>−1</sub> − <em>B</em><sub><em>t</em>−1</sub> + <em>x</em><sub><em>t</em></sub> − <em>d</em><sub><em>t</em></sub> &nbsp;=&nbsp; <em>I</em><sub><em>t</em></sub> − <em>B</em><sub><em>t</em></sub> &nbsp;&nbsp; for every <em>t</em> ∈ <em>T</em></p>
<p>with <em>I</em><sub>0</sub> given and <em>B</em><sub>0</sub> = 0.</p>
</div>
<div class="dots">
<ul>
<li><strong>The net stock position</strong> Positive means stock on hand at the close of the period, negative means stock owed to a customer.</li>
<li><strong>The same law, a new boundary</strong> Drawn around a period rather than around a vessel.</li>
<li><strong>Patterns 1 and 2 together</strong> Written once, and expanded over the ordered set of periods.</li>
</ul>
</div>
</div></div>
</section>
<section id="start-or-end-of-period-say-which-because-the-answer-changes" class="slide level2 tint" data-background-color="#F3F0EB">
<h2>Start or end of period? Say which, because the answer changes</h2>
<div class="kicker c-rust">
<p>This is ambiguity 1 from Activity 1</p>
</div>
<div class="columns">
<div class="column" style="width:49%;">
<div class="cards">
<div class="card c-teal">
<p><span class="eyebrow">Convention A — used here</span></p>
<h3 id="measure-at-the-end">Measure at the <strong>end</strong></h3>
<p><em>I</em><sub><em>t</em></sub> is the stock <em>after</em> period <em>t</em> has produced and shipped.</p>
<p><em>I</em><sub><em>t</em>−1</sub> + <em>x</em><sub><em>t</em></sub> − <em>d</em><sub><em>t</em></sub> = <em>I</em><sub><em>t</em></sub></p>
<p>Holding is charged on what is <strong>left over at the close</strong> of the period, so material that arrives and ships inside the same period is never charged holding.</p>
</div>
</div>
</div><div class="column" style="width:49%;">
<div class="cards">
<div class="card c-plum">
<p><span class="eyebrow">Convention B</span></p>
<h3 id="measure-at-the-start">Measure at the <strong>start</strong></h3>
<p><em>Ĩ</em><sub><em>t</em></sub> is the stock <em>before</em> period <em>t</em> produces and ships, so <em>Ĩ</em><sub><em>t</em></sub> = <em>I</em><sub><em>t</em>−1</sub>.</p>
<p><em>Ĩ</em><sub><em>t</em></sub> + <em>x</em><sub><em>t</em></sub> − <em>d</em><sub><em>t</em></sub> = <em>Ĩ</em><sub><em>t</em>+1</sub></p>
<p>Holding is charged on the <strong>opening</strong> stock, so the 20 t on hand at the planning date is charged in period 1 — and the closing stock of the last period is not charged at all.</p>
</div>
</div>
</div></div>
<div class="foot">
<div class="punch">
<p>Both are correct. They are not the same model: they differ by one period of holding charge at each end of the horizon, so they return <strong>different total costs and can return different plans</strong>. What is wrong is failing to say which one you used, because the next engineer to touch the sheet will assume the other.</p>
</div>
</div>
</section>
<section id="backlog-the-horizon-end-and-two-kinds-of-capacity" class="slide level2">
<h2>Backlog, the horizon end, and two kinds of capacity</h2>
<div class="kicker c-teal">
<p>Three modeling decisions, one slide</p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<div class="cards">
<div class="card c-teal">
<p><strong>Why split the net position into two variables</strong></p>
<p>A single free variable <em>s</em><sub><em>t</em></sub> = <em>I</em><sub><em>t</em></sub> − <em>B</em><sub><em>t</em></sub> would be simpler, but it could not be <strong>priced</strong>: holding costs <em>h</em>, shortage costs <em>b</em>, and <em>b</em> ≠ <em>h</em>. Splitting into <em>I</em><sub><em>t</em></sub> ≥ 0 and <em>B</em><sub><em>t</em></sub> ≥ 0 keeps the model linear while pricing the two directions differently.</p>
</div>
<div class="card c-amber">
<p><strong>Complementarity comes free</strong></p>
<p>Because <em>h</em> &gt; 0, <em>b</em> &gt; 0 and this is a minimization, no optimal solution ever has <em>I</em><sub><em>t</em></sub> &gt; 0 and <em>B</em><sub><em>t</em></sub> &gt; 0 at once — carrying stock and owing stock at the same time costs money and changes nothing. <strong>No binary variable is needed.</strong> The cost structure enforces it.</p>
</div>
</div>
</div><div class="column" style="width:48%;">
<div class="cards">
<div class="card c-rust">
<p><strong>The horizon-end condition</strong></p>
<p><em>B</em><sub>|<em>T</em>|</sub> = 0</p>
<p>This is what makes the plan honest. Without it, the model pushes all the difficult demand past the end of the horizon and reports a cost that cannot be achieved.</p>
</div>
<div class="card c-slate">
<p><strong>Capacity: per period, or across the horizon</strong></p>
<p><em>x</em><sub><em>t</em></sub> ≤ <em>C</em><sub><em>t</em></sub> for every <em>t</em> &nbsp;&nbsp; versus &nbsp;&nbsp; Σ<sub><em>t</em></sub> <em>x</em><sub><em>t</em></sub> ≤ <em>C</em></p>
<p>Line hours reset each month: one inequality per period. A fixed catalyst allocation consumed once: a single inequality. Today’s model uses the first.</p>
</div>
</div>
</div></div>
</section>
<section id="the-complete-single-product-model-family-by-family" class="slide level2">
<h2>The complete single-product model, family by family</h2>
<div class="kicker c-amber">
<p>Everything so far, on one slide</p>
</div>
<div class="spec">
<p><span class="eyebrow">Minimize total cost over the horizon</span></p>
<p>min &nbsp; Σ<sub><em>t</em></sub> ( <em>c</em><sub><em>t</em></sub> <em>x</em><sub><em>t</em></sub> + <em>h</em> <em>I</em><sub><em>t</em></sub> + <em>b</em> <em>B</em><sub><em>t</em></sub> ) &nbsp;&nbsp; [USD] &nbsp;&nbsp; over <em>x</em>, <em>I</em>, <em>B</em> ≥ 0</p>
</div>
<div class="columns">
<div class="column" style="width:60%;">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Constraint family</th>
<th></th>
<th>Pattern</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>I</em><sub><em>t</em>−1</sub> − <em>B</em><sub><em>t</em>−1</sub> + <em>x</em><sub><em>t</em></sub> − <em>d</em><sub><em>t</em></sub> = <em>I</em><sub><em>t</em></sub> − <em>B</em><sub><em>t</em></sub></td>
<td>for every <em>t</em></td>
<td>balance, <strong>P2 + P4</strong></td>
</tr>
<tr class="even">
<td><em>x</em><sub><em>t</em></sub> ≤ <em>C</em><sub><em>t</em></sub></td>
<td>for every <em>t</em></td>
<td>capacity, <strong>P3</strong></td>
</tr>
<tr class="odd">
<td><em>B</em><sub>|<em>T</em>|</sub> = 0</td>
<td>once</td>
<td>horizon end</td>
</tr>
<tr class="even">
<td><em>x</em><sub><em>t</em></sub>, <em>I</em><sub><em>t</em></sub>, <em>B</em><sub><em>t</em></sub> ≥ 0</td>
<td>for every <em>t</em></td>
<td>bounds</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:38%;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Size, for six periods</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Decision variables</td>
<td><strong>18</strong></td>
</tr>
<tr class="even">
<td>Constraints</td>
<td><strong>13</strong></td>
</tr>
</tbody>
</table>
<div class="note">
<p>Three variable families times six periods. Six balances, six capacities, one horizon-end condition.</p>
</div>
<div class="flag">
<p>Everything is linear and continuous, so this is an <strong>LP</strong> and the Week 1 vertex argument applies unchanged. The whole model is patterns 1 to 4 and nothing else.</p>
</div>
</div></div>
</section>
<section id="the-same-model-in-the-spreadsheet-periods-across-columns" class="slide level2 tint" data-background-color="#F3F0EB">
<h2>The same model in the spreadsheet: periods across columns</h2>
<div class="kicker c-teal">
<p>The sheet you are about to complete</p>
</div>
<div class="columns">
<div class="column" style="width:52%;">
<svg viewbox="0 0 560 320" style="width:100%;max-width:600px" role="img" aria-label="A spreadsheet layout with the six periods running across columns C to H, three blue rows of given data, three green rows of changing cells for production inventory and backlog, and two teal constraint row blocks below for the balance and the capacity.">
<g font-size="13" fill="#66727C" text-anchor="middle"><text x="78" y="26">B</text><text x="181" y="26">C</text><text x="243" y="26">D</text><text x="305" y="26">E</text><text x="367" y="26">F</text><text x="429" y="26">G</text><text x="491" y="26">H</text></g> <g stroke="#B9C1C6" stroke-width="1"><rect x="8" y="34" width="142" height="26" fill="#B9C1C6" fill-opacity="0.45"></rect><rect x="150" y="34" width="372" height="26" fill="#B9C1C6" fill-opacity="0.45"></rect></g> <g font-size="13" fill="#1C242B" text-anchor="middle"><text x="181" y="52">1</text><text x="243" y="52">2</text><text x="305" y="52">3</text><text x="367" y="52">4</text><text x="429" y="52">5</text><text x="491" y="52">6</text></g> <text x="14" y="52" font-size="13" fill="#1C242B">period, row 5</text> <g stroke="#B9C1C6" stroke-width="1" fill="#FFFFFF"><rect x="8" y="60" width="142" height="26"></rect><rect x="8" y="86" width="142" height="26"></rect><rect x="8" y="112" width="142" height="26"></rect><rect x="150" y="60" width="372" height="26"></rect><rect x="150" y="86" width="372" height="26"></rect><rect x="150" y="112" width="372" height="26"></rect></g> <g font-size="13" fill="#5A91BE"><text x="14" y="78">demand dₜ · row 6</text><text x="14" y="104">capacity Cₜ · row 7</text><text x="14" y="130">unit cost cₜ · row 8</text></g> <g font-size="13" fill="#5A91BE" text-anchor="middle"><text x="181" y="78">120</text><text x="243" y="78">150</text><text x="305" y="78">180</text><text x="367" y="78">210</text><text x="429" y="78">160</text><text x="491" y="78">130</text><text x="336" y="104">170 in every period</text><text x="181" y="130">42</text><text x="243" y="130">42</text><text x="305" y="130">45</text><text x="367" y="130">48</text><text x="429" y="130">46</text><text x="491" y="130">43</text></g> <g stroke="#83A462" stroke-width="1.4" fill="#83A462" fill-opacity="0.22"><rect x="8" y="146" width="142" height="26"></rect><rect x="8" y="172" width="142" height="26"></rect><rect x="8" y="198" width="142" height="26"></rect><rect x="150" y="146" width="372" height="26"></rect><rect x="150" y="172" width="372" height="26"></rect><rect x="150" y="198" width="372" height="26"></rect></g> <g font-size="13" fill="#1C242B"><text x="14" y="164">production xₜ · row 16</text><text x="14" y="190">inventory Iₜ · row 17</text><text x="14" y="216">backlog Bₜ · row 18</text></g> <text x="336" y="190" font-size="13" fill="#333F4A" text-anchor="middle">C16:H18 — 18 changing cells</text> <g stroke="#0F6E6B" stroke-width="1.6" fill="#0F6E6B" fill-opacity="0.10"><rect x="8" y="236" width="250" height="30"></rect><rect x="8" y="270" width="250" height="30"></rect></g> <g font-size="13" fill="#1C242B"><text x="16" y="255">balance C28:C33 = E28:E33</text><text x="16" y="289">capacity C34:C39 ≤ E34:E39</text></g> <rect x="272" y="236" width="250" height="64" fill="#DFC98F" fill-opacity="0.45" stroke="#E29A2D" stroke-width="1.6"></rect> <text x="282" y="256" font-size="13" fill="#1C242B">C40: B₆ = 0 · the only scalar row</text> <text x="282" y="277" font-size="13" fill="#1C242B">C24: objective, Min, sum of C21:C23</text> <text x="282" y="296" font-size="12" fill="#66727C">t − 1 is the column to the left</text>
</svg>
</div><div class="column" style="width:46%;">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Algebraic symbol</th>
<th>Range</th>
<th>Pyomo component</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><em>t</em> ∈ <em>T</em></td>
<td><code>C5:H5</code></td>
<td><code>Set(..., ordered=True)</code></td>
</tr>
<tr class="even">
<td><em>d</em><sub><em>t</em></sub>, <em>C</em><sub><em>t</em></sub>, <em>c</em><sub><em>t</em></sub></td>
<td><code>C6:H8</code></td>
<td><code>Param(m.T, ...)</code></td>
</tr>
<tr class="odd">
<td><em>h</em>, <em>b</em>, <em>I</em><sub>0</sub>, <em>B</em><sub>0</sub></td>
<td><code>C9:H10</code>, <code>C11:C12</code></td>
<td>scalar <code>Param</code></td>
</tr>
<tr class="even">
<td><em>x</em>, <em>I</em>, <em>B</em> ≥ 0</td>
<td><code>C16:H18</code></td>
<td>three <code>Var(m.T, ...)</code></td>
</tr>
<tr class="odd">
<td>balance ∀ <em>t</em></td>
<td><code>C28:C33</code></td>
<td><code>Constraint(m.T, rule=...)</code></td>
</tr>
<tr class="even">
<td><em>x</em><sub><em>t</em></sub> ≤ <em>C</em><sub><em>t</em></sub></td>
<td><code>C34:C39</code></td>
<td><code>Constraint(m.T, ...)</code></td>
</tr>
<tr class="odd">
<td>objective</td>
<td><code>C24</code></td>
<td><code>Objective(sense=minimize)</code></td>
</tr>
</tbody>
</table>
<div class="note">
<p><strong>The transposition.</strong> In Week 1 the model ran down the rows. Here periods run across columns, so each constraint family becomes a <em>block of rows</em>. Only the layout changed.</p>
</div>
</div></div>
</section>
<section id="build-it-and-predict-it" class="slide level2 dark divider c-amber" data-background-color="#1C242B">
<h2>Build it and predict it</h2>
<div class="kicker">
<p>Activity 2 · 15 minutes · pairs, one computer</p>
</div>
<div class="lede">
<p>The number is on the board.<br> Forty-two thousand and eighty.</p>
</div>
<div class="flag">
<p>If your sheet does not say that, your sheet is wrong — and finding out why is more useful than anything I could tell you in the next eight minutes.</p>
</div>
</section>
<section id="complete-the-sheet-then-predict" class="slide level2">
<h2>Complete the sheet, then predict</h2>
<div class="kicker c-amber">
<p>Activity 2 · 15 minutes · pairs, one computer</p>
</div>
<div class="columns">
<div class="column" style="width:53%;">
<div class="cards">
<div class="card c-teal">
<p><span class="eyebrow">Data already on the sheet</span></p>
<p>Six monthly periods. Demand <strong>120, 150, 180, 210, 160, 130</strong> t. Line capacity <strong>170</strong> t/month throughout. Production cost <strong>42, 42, 45, 48, 46, 43</strong> USD/t. Holding <strong>6</strong> USD/t/month, backlog <strong>45</strong> USD/t/month, opening stock <strong>20</strong> t, and <em>B</em><sub>6</sub> = 0.</p>
</div>
<div class="card c-slate">
<p><span class="eyebrow">OpenSolver setup</span></p>
<p>Objective <code>$C$24</code>, <strong>Min</strong> · changing cells <code>$C$16:$H$18</code> · balance <code>$C$28:$C$33 = $E$28:$E$33</code> · capacity <code>$C$34:$C$39 ≤ $E$34:$E$39</code> · <code>$C$40 = $E$40</code> · engine CBC · tick <strong>Sensitivity Analysis</strong>.</p>
</div>
</div>
</div><div class="column" style="width:45%;">
<div class="numbered n3">
<ol type="1">
<li><strong>0 to 8 min</strong> Open <code>W02_multiperiod_planning_STUDENT.xlsx</code>. Complete the yellow cells: the balance row for each period, and the objective. Run Solver.</li>
<li><strong>8 to 11 min · on paper, hands off the keyboard</strong> If the period-4 capacity is raised by one tonne, by how much does total cost fall? Write a number.</li>
<li><strong>11 to 15 min</strong> Change it, re-solve, compare. Then explain why the same change in period 1 does nothing at all.</li>
</ol>
</div>
<div class="punch">
<p>Target: total cost <strong>42,080.00 USD</strong>.</p>
</div>
</div></div>
</section>
<section id="section-1" class="slide level2 dark break c-amber" data-background-color="#1C242B">
<h2>&nbsp;</h2>
<div class="vcenter">
<div class="break-circle">
<p><span>10</span></p>
</div>
<div class="big-label">
<p>minute break</p>
</div>
<div class="note">
<p>Then: what the plan you just solved actually says, the measured value of planning ahead, a second product on the same reactor, where the spreadsheet stops being the right tool, and HW1</p>
</div>
</div>
</section>
<section id="multi-product-look-ahead-and-the-limits-of-the-sheet" class="slide level2 dark divider c-teal" data-background-color="#1C242B">
<h2>Multi-product, look-ahead, and the limits of the sheet</h2>
<div class="kicker">
<p>Lecture block 3 · 45 minutes</p>
</div>
<div class="lede">
<p>What the plan says, what planning ahead is worth,<br> and where this tool stops.</p>
</div>
</section>
<section id="reading-the-solution-where-inventory-is-built-and-why" class="slide level2">
<h2>Reading the solution: where inventory is built, and why</h2>
<div class="kicker c-amber">
<p>Activity 2, revealed</p>
</div>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Period</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Demand <em>d</em><sub><em>t</em></sub>, t</td>
<td>120</td>
<td>150</td>
<td>180</td>
<td>210</td>
<td>160</td>
<td>130</td>
</tr>
<tr class="even">
<td>Capacity <em>C</em><sub><em>t</em></sub>, t</td>
<td>170</td>
<td>170</td>
<td>170</td>
<td>170</td>
<td>170</td>
<td>170</td>
</tr>
<tr class="odd">
<td>Unit cost <em>c</em><sub><em>t</em></sub>, USD/t</td>
<td>42</td>
<td>42</td>
<td>45</td>
<td>48</td>
<td>46</td>
<td>43</td>
</tr>
<tr class="even">
<td><strong>Production <em>x</em><sub><em>t</em></sub>, t</strong></td>
<td><strong>130</strong></td>
<td><strong>170</strong></td>
<td><strong>170</strong></td>
<td><strong>170</strong></td>
<td><strong>160</strong></td>
<td><strong>130</strong></td>
</tr>
<tr class="odd">
<td><strong>Inventory <em>I</em><sub><em>t</em></sub>, t</strong></td>
<td><strong>30</strong></td>
<td><strong>50</strong></td>
<td><strong>40</strong></td>
<td><strong>0</strong></td>
<td><strong>0</strong></td>
<td><strong>0</strong></td>
</tr>
<tr class="even">
<td>Backlog <em>B</em><sub><em>t</em></sub>, t</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
</tbody>
</table>
<div class="columns">
<div class="column" style="width:46%;">
<div class="note">
<p>Total cost <strong>42,080.00 USD</strong> = 41,360.00 production + 720.00 holding + 0 backlog. Opening stock 20 t. Capacity binds in periods 2, 3 and 4 only.</p>
</div>
</div><div class="column" style="width:52%;">
<div class="flag">
<p><strong>Why the plan pre-builds.</strong> Periods 3 and 4 together demand 390 t against a combined capacity of 340 t — a shortfall of 50 t that <em>physically</em> must be made earlier. Closing inventory at the end of period 2 is exactly 50 t: the shortfall, and nothing more. It is <strong>not</strong> price arbitrage. Producing in period 2 at 42 and holding two months costs 42 + 2(6) = 54 USD/t, worse than making it in period 4 at 48. The plant builds stock <em>in spite of</em> the price signal.</p>
</div>
</div></div>
</section>
<section id="reading-the-capacity-duals-what-to-buy-and-when" class="slide level2">
<h2>Reading the capacity duals: what to buy, and when</h2>
<div class="kicker c-teal">
<p>The practical output of the whole model</p>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th>Period</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Capacity slack, t</td>
<td>40</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>10</td>
<td>40</td>
</tr>
<tr class="even">
<td><strong>Dual, USD/t</strong></td>
<td><strong>0</strong></td>
<td><strong>6</strong></td>
<td><strong>9</strong></td>
<td><strong>12</strong></td>
<td><strong>0</strong></td>
<td><strong>0</strong></td>
</tr>
</tbody>
</table>
<div class="columns">
<div class="column" style="width:49%;">
<div class="cards">
<div class="card c-rust">
<p><strong>Where the debottlenecking budget goes</strong></p>
<p><strong>Period 4 first, at 12 USD per tonne of extra capacity.</strong> Nowhere near periods 1, 5 or 6, where extra capacity is worth exactly zero.</p>
<p><em>A capital request must name the period, not just the resource.</em></p>
</div>
</div>
</div><div class="column" style="width:49%;">
<div class="cards">
<div class="card c-teal">
<p><strong>Binding in a period is not binding across the horizon</strong></p>
<p>Total capacity over six periods is <strong>1,020 t</strong> against total demand of <strong>950 t</strong>, with 20 t of opening stock. In aggregate the horizon is comfortable. It is only <em>period by period</em> that the plan is tight, and only in three periods of six.</p>
<p>An annual capacity number would have reported no problem at all.</p>
</div>
</div>
</div></div>
<div class="foot">
<div class="note">
<p>Pyomo returns a negative dual for a ≤ constraint in a minimization, so the magnitude is the <em>cost reduction</em> from one extra tonne. The OpenSolver sensitivity report gives the same magnitudes, and every one is reproduced in the notebook by re-solving with one extra tonne.</p>
</div>
</div>
</section>
<section id="the-value-of-look-ahead-measured" class="slide level2">
<h2>The value of look-ahead, measured</h2>
<div class="kicker c-amber">
<p>The most persuasive number of the week</p>
</div>
<div class="columns">
<div class="column" style="width:55%;">
<div class="lede">
<p>The myopic benchmark is a rule with no look-ahead: in each period, produce only what is needed <strong>now</strong>, up to capacity.</p>
</div>
<table class="caption-top">
<thead>
<tr class="header">
<th>Period</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Production, t</td>
<td>100</td>
<td>150</td>
<td>170</td>
<td>170</td>
<td>170</td>
<td>170</td>
</tr>
<tr class="even">
<td>Backlog, t</td>
<td>0</td>
<td>0</td>
<td>10</td>
<td>50</td>
<td>40</td>
<td>0</td>
</tr>
</tbody>
</table>
<div class="cards">
<div class="card c-rust">
<p><strong>This is not a straw man</strong></p>
<p>A plant that runs a monthly production meeting, looks at this month’s order book, and fills it, is executing exactly this rule. Nobody in that meeting is being careless. The horizon simply is not on the table.</p>
</div>
</div>
</div><div class="column" style="width:43%;">
<div class="spec">
<p><span class="eyebrow">The comparison</span></p>
<dl>
<dt>Myopic cost</dt>
<dd>
<strong>45,940.00</strong> USD
</dd>
<dt>Optimal cost</dt>
<dd>
<strong>42,080.00</strong> USD
</dd>
<dt>Value of look-ahead</dt>
<dd>
<strong>3,860.00</strong> USD — <strong>8.4 %</strong>
</dd>
</dl>
</div>
<div class="punch">
<p>8.4 percent of cost, from no capital, no new equipment and no new people.</p>
</div>
<div class="note">
<p>Both plans make the same total tonnage: <strong>930 t</strong>. The myopic rule falls behind in period 3 and then pays 45 USD/t/month in periods 3, 4 and 5 on a backlog that peaks at 50 t.</p>
</div>
</div></div>
</section>
<section id="myopic-versus-look-ahead-period-by-period" class="slide level2">
<h2>Myopic versus look-ahead, period by period</h2>
<div class="kicker c-teal">
<p>Same tonnage, different timing</p>
</div>
<svg viewbox="0 0 540 330" style="width:100%;max-width:780px" role="img" aria-label="Grouped bar chart of production in each of six periods, comparing the look-ahead plan in teal with the myopic plan in rust, against a dotted demand line and a dashed amber capacity line at 170 tonnes per month.">
<line x1="70" y1="300" x2="510" y2="300" stroke="#333F4A" stroke-width="2"></line><line x1="70" y1="300" x2="70" y2="40" stroke="#333F4A" stroke-width="2"></line> <g stroke="#B9C1C6" stroke-width="1"><line x1="70" y1="240.9" x2="510" y2="240.9"></line><line x1="70" y1="181.8" x2="510" y2="181.8"></line><line x1="70" y1="122.7" x2="510" y2="122.7"></line><line x1="70" y1="63.6" x2="510" y2="63.6"></line></g> <g font-size="13" fill="#66727C" text-anchor="end"><text x="62" y="305">0</text><text x="62" y="246">50</text><text x="62" y="187">100</text><text x="62" y="128">150</text><text x="62" y="68">200</text></g> <g fill="#0F6E6B"><rect x="86" y="146.4" width="24" height="153.6"></rect><rect x="156" y="99.1" width="24" height="200.9"></rect><rect x="226" y="99.1" width="24" height="200.9"></rect><rect x="296" y="99.1" width="24" height="200.9"></rect><rect x="366" y="110.9" width="24" height="189.1"></rect><rect x="436" y="146.4" width="24" height="153.6"></rect></g> <g fill="#BE654C"><rect x="114" y="181.8" width="24" height="118.2"></rect><rect x="184" y="122.7" width="24" height="177.3"></rect><rect x="254" y="99.1" width="24" height="200.9"></rect><rect x="324" y="99.1" width="24" height="200.9"></rect><rect x="394" y="99.1" width="24" height="200.9"></rect><rect x="464" y="99.1" width="24" height="200.9"></rect></g> <line x1="70" y1="99.1" x2="510" y2="99.1" stroke="#E29A2D" stroke-width="2.5" stroke-dasharray="7 5"></line> <text x="506" y="93" font-size="13" fill="#E29A2D" text-anchor="end">capacity 170 t/month</text> <polyline points="113,158.2 183,122.7 253,87.3 323,51.8 393,110.9 463,146.4" fill="none" stroke="#333F4A" stroke-width="2.2" stroke-dasharray="3 4"></polyline> <g fill="#FFFFFF" stroke="#333F4A" stroke-width="2"><circle cx="113" cy="158.2" r="4"></circle><circle cx="183" cy="122.7" r="4"></circle><circle cx="253" cy="87.3" r="4"></circle><circle cx="323" cy="51.8" r="4"></circle><circle cx="393" cy="110.9" r="4"></circle><circle cx="463" cy="146.4" r="4"></circle></g> <text x="345" y="45" font-size="13" fill="#333F4A">demand</text> <g font-size="13" fill="#66727C" text-anchor="middle"><text x="113" y="318">1</text><text x="183" y="318">2</text><text x="253" y="318">3</text><text x="323" y="318">4</text><text x="393" y="318">5</text><text x="463" y="318">6</text></g> <text x="16" y="26" font-size="14" fill="#1C242B">production, t · period 1 to 6</text> <g><rect x="300" y="14" width="18" height="12" fill="#0F6E6B"></rect><text x="324" y="25" font-size="13" fill="#333F4A">look-ahead</text><rect x="410" y="14" width="18" height="12" fill="#BE654C"></rect><text x="434" y="25" font-size="13" fill="#333F4A">myopic</text></g>
</svg>
<div class="foot">
<div class="punch">
<p>The teal bars sit <em>above</em> demand in periods 1 and 2 and below it in period 4. The rust bars sit <em>on</em> demand until period 3 and then sit on the capacity line for the rest of the horizon, never catching up until the last month. Same 930 tonnes. 3,860.00 USD apart.</p>
</div>
</div>
</section>
<section id="a-second-product-on-the-same-reactor" class="slide level2">
<h2>A second product on the same reactor</h2>
<div class="kicker c-amber">
<p>Resource linking</p>
</div>
<div class="columns">
<div class="column" style="width:52%;">
<div class="spec">
<p><span class="eyebrow">What changes</span></p>
<p>Every variable and every balance gains a product index: <em>x</em><sub><em>p</em>,<em>t</em></sub>, <em>I</em><sub><em>p</em>,<em>t</em></sub>, <em>B</em><sub><em>p</em>,<em>t</em></sub>. The balance and the line capacity are written once <strong>per product</strong> and are otherwise unchanged.</p>
<p>One genuinely new constraint appears, indexed over <strong>time only</strong>:</p>
<p>Σ<sub><em>p</em></sub> <em>ρ</em><sub><em>p</em></sub> <em>x</em><sub><em>p</em>,<em>t</em></sub> &nbsp;≤&nbsp; <em>R</em><sub><em>t</em></sub> &nbsp;&nbsp; for every <em>t</em></p>
</div>
<div class="flag">
<p>That is pattern 3 and pattern 4 in the same row: a shared resource limiting a sum, whose index spans both product blocks.</p>
</div>
</div><div class="column" style="width:46%;">
<table class="caption-top">
<thead>
<tr class="header">
<th></th>
<th>Additive</th>
<th>Binder</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Line capacity, t/month</td>
<td>170</td>
<td>150</td>
</tr>
<tr class="even">
<td>Holding, USD/t/month</td>
<td>6</td>
<td>8</td>
</tr>
<tr class="odd">
<td>Backlog, USD/t/month</td>
<td>45</td>
<td>60</td>
</tr>
<tr class="even">
<td>Reactor <em>ρ</em><sub><em>p</em></sub>, h/t</td>
<td>1.0</td>
<td>1.4</td>
</tr>
<tr class="odd">
<td>Opening stock, t</td>
<td>20</td>
<td>10</td>
</tr>
</tbody>
</table>
<div class="cards">
<div class="card c-rust">
<p><strong>Reactor hours available: 330 per month</strong></p>
<p>Just-in-time would need 246.0, 304.0, <strong>362.0</strong>, <strong>406.0</strong>, 328.0, 270.0 h. Periods 3 and 4 are impossible without shifting work earlier, so the reactor constraint will bind.</p>
</div>
</div>
</div></div>
</section>
<section id="what-sharing-the-reactor-costs" class="slide level2">
<h2>What sharing the reactor costs</h2>
<div class="kicker c-teal">
<p>The coupling constraint is what makes this one problem</p>
</div>
<div class="columns">
<div class="column" style="width:47%;">
<div class="spec">
<p><span class="eyebrow">Measured</span></p>
<dl>
<dt>Uncoupled, no reactor limit</dt>
<dd>
<strong>83,330.00</strong> USD
</dd>
<dt>Coupled, reactor ≤ 330 h</dt>
<dd>
<strong>83,930.86</strong> USD
</dd>
<dt>Cost of the shared reactor</dt>
<dd>
<strong>600.86</strong> USD
</dd>
</dl>
</div>
<div class="note">
<p>The uncoupled plan is not a plan at all: it needs <strong>366.0 reactor hours in period 4</strong> and only 330 exist.</p>
</div>
</div><div class="column" style="width:51%;">
<div class="cards">
<div class="card c-slate">
<p><strong>Without the shared rows the model is block diagonal</strong></p>
<p>It separates <em>exactly</em> into one independent LP per product. The reactor links the blocks, destroys separability, and creates the real decision: in a period when reactor time is short, <strong>which product gets it</strong>.</p>
</div>
<div class="card c-teal">
<p><strong>600.86 USD over six months</strong></p>
<p>That is what the plant pays for owning one reactor train instead of two, and it is the figure to weigh against annualized capacity. Sharing is <strong>cheap</strong> here, because inventory smooths the peaks.</p>
</div>
</div>
</div></div>
<div class="foot">
<div class="punch">
<p>The shadow price of reactor time is periodic, not constant: 0, 5.7143, 9.2857, <strong>12.2857</strong>, 0, 0 USD/h. Only periods 2, 3 and 4 bind. Re-solving with 331 hours in period 4 gives 83,918.5714 USD — exactly 12.2857 below the base case, which is the definition of the dual, not a coincidence.</p>
</div>
</div>
</section>
<section id="where-the-spreadsheet-stops-working" class="slide level2 tint" data-background-color="#F3F0EB">
<h2>Where the spreadsheet stops working</h2>
<div class="kicker c-rust">
<p>The argument is about auditability, not arithmetic</p>
</div>
<div class="columns">
<div class="column" style="width:45%;">
<table class="caption-top">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th></th>
<th>Today: 6 periods, 1 product</th>
<th>52 periods, 3 products, shared reactor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Changing cells</td>
<td>18</td>
<td><strong>468</strong></td>
</tr>
<tr class="even">
<td>Balance rows</td>
<td>6</td>
<td><strong>156</strong></td>
</tr>
<tr class="odd">
<td>Capacity rows</td>
<td>6</td>
<td><strong>156</strong></td>
</tr>
<tr class="even">
<td>Reactor rows</td>
<td>0</td>
<td>52</td>
</tr>
<tr class="odd">
<td>Fits on a screen</td>
<td>yes</td>
<td>no</td>
</tr>
</tbody>
</table>
<div class="note">
<p>3 × 3 × 52 = 468 changing cells; 3 × 52 = 156 balance rows; 3 × 52 = 156 capacity rows; 52 reactor rows. These are the closing note on the workbook’s <code>Readme</code> sheet.</p>
</div>
</div><div class="column" style="width:53%;">
<div class="cards">
<div class="card c-rust">
<p><strong>None of that is <em>hard</em>. It is simply not auditable</strong></p>
<p><strong>No diffing, no unit tests, no scenario loop.</strong> There is no way to prove that the formula in one column of 52 is the same as in the other 51 — and one mis-anchored <code>$</code> produces a plan the sheet reports as feasible and the plant cannot execute.</p>
<p>Adding a fourth product means rebuilding the sheet. Adding a warehouse limit means inserting 52 rows in the middle and repairing every reference below. Re-solving under 20 demand scenarios means 20 copies of the workbook.</p>
</div>
<div class="card c-teal">
<p><strong>The plan from here</strong></p>
<p><strong>Week 3 stays in the spreadsheet</strong>, because a cost matrix is a spreadsheet. <strong>Week 4 is the crossover</strong>, because pooling multiplies a flow by a quality and a spreadsheet cannot handle it at all. In Pyomo, 6 periods and 52 periods are the same six lines of code.</p>
</div>
</div>
</div></div>
</section>
<section id="the-same-model-in-pyomo-side-by-side" class="slide level2">
<h2>The same model in Pyomo, side by side</h2>
<div class="kicker c-teal">
<p>Two implementations, one number</p>
</div>
<div class="columns">
<div class="column" style="width:49%;">
<div class="cards">
<div class="card c-sage">
<p><span class="eyebrow">Spreadsheet · W02_multiperiod_planning</span></p>
<p><code>C5:H5</code> six period headers</p>
<p><code>C6:H8</code> demand, capacity, unit cost</p>
<p><code>C16:H18</code> changing cells, 18 of them</p>
<p><code>C28:C33</code> balance rows, one per period</p>
<p><code>C34:C39</code> capacity rows, one per period</p>
<p><code>C40</code> &nbsp; <em>B</em><sub>6</sub> = 0</p>
<p><code>C24</code> &nbsp; objective, minimize</p>
<p><em>Adding a period means inserting a column and repairing every formula that crosses it.</em></p>
</div>
</div>
</div><div class="column" style="width:49%;">
<div class="cards">
<div class="card c-teal">
<p><span class="eyebrow">Pyomo · W02_modeling1_linear_multiperiod</span></p>
<p><code>m.T = pyo.Set(initialize=T, ordered=True)</code></p>
<p><code>m.d = pyo.Param(m.T, initialize=...)</code></p>
<p><code>m.x = pyo.Var(m.T, domain=NonNegativeReals)</code></p>
<p><code>m.I = pyo.Var(m.T, domain=NonNegativeReals)</code></p>
<p><code>m.B = pyo.Var(m.T, domain=NonNegativeReals)</code></p>
<p><code>m.balance = pyo.Constraint(m.T, rule=...)</code></p>
<p><code>m.capacity = pyo.Constraint(m.T, rule=...)</code></p>
<p><code>m.cost = pyo.Objective(..., sense=pyo.minimize)</code></p>
<p><em>Adding a period means adding one entry to</em> <code>T</code>.</p>
</div>
</div>
</div></div>
<div class="foot">
<div class="punch">
<p>Both routes report <strong>42,080.00 USD</strong>, and that agreement is the verification. If the spreadsheet and the notebook ever disagree, the spreadsheet is wrong.</p>
</div>
</div>
</section>
<section id="hw1-is-released-today" class="slide level2">
<h2>HW1 is released today</h2>
<div class="kicker c-amber">
<p>Due Week 4</p>
</div>
<div class="columns">
<div class="column" style="width:52%;">
<div class="numbered n4">
<ol type="1">
<li><strong>Released today, Week 2. Due Week 4.</strong> On myCourseVille at the end of this session.</li>
<li><strong>Linear and network model construction.</strong> The linear half rests on today; the network half needs Week 3, so start with the linear half now.</li>
<li><strong>Every question that asks for a model asks for the structured specification first</strong>, exactly as in Activity 1, and marks it separately.</li>
<li><strong>One question asks for a multiperiod plan</strong> built in OpenSolver and reproduced in Pyomo, with the two answers compared.</li>
</ol>
</div>
</div><div class="column" style="width:46%;">
<div class="cards">
<div class="card c-rust">
<p><strong>The instruction that carries the most marks</strong></p>
<p><strong>Write the specification before any algebra.</strong></p>
<p>A correct model with no specification loses marks. A specification that states its assumptions and its start-versus-end convention earns them even where the algebra slips.</p>
</div>
<div class="card c-teal">
<p><strong>Two habits to carry into it</strong></p>
<p>A unit on every symbol, and a bound on every variable. Both are checkable by a reader in thirty seconds, and both catch the errors a solver never reports.</p>
</div>
</div>
</div></div>
</section>
<section id="numbers-established-today" class="slide level2">
<h2>Numbers established today</h2>
<div class="kicker c-teal">
<p>Summary</p>
</div>
<div class="columns">
<div class="column" style="width:50%;">
<table class="caption-top">
<thead>
<tr class="header">
<th>Quantity</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Warm-up optimum</td>
<td>(24, 20) t/week, <strong>28,280.00</strong></td>
</tr>
<tr class="even">
<td>Its duals, mix / pur. / fill</td>
<td>0 / 90 / 430 USD/h</td>
</tr>
<tr class="odd">
<td>Six-period optimal cost</td>
<td><strong>42,080.00</strong> = 41,360.00 + 720.00 + 0</td>
</tr>
<tr class="even">
<td>Production plan, t</td>
<td>130, 170, 170, 170, 160, 130</td>
</tr>
<tr class="odd">
<td>Inventory plan, t</td>
<td>30, 50, 40, 0, 0, 0</td>
</tr>
<tr class="even">
<td>Capacity duals, USD/t</td>
<td>0, 6, 9, 12, 0, 0</td>
</tr>
<tr class="odd">
<td>One extra tonne in period 4</td>
<td>42,068.00 USD</td>
</tr>
<tr class="even">
<td>Myopic cost, and the gap</td>
<td>45,940.00 USD</td>
</tr>
<tr class="odd">
<td><strong>Value of look-ahead</strong></td>
<td><strong>3,860.00 USD, 8.4 %</strong></td>
</tr>
<tr class="even">
<td>Two products, uncoupled / coupled</td>
<td>83,330.00 / 83,930.86 USD</td>
</tr>
<tr class="odd">
<td>Cost of sharing the reactor</td>
<td><strong>600.86</strong> USD</td>
</tr>
<tr class="even">
<td>52 periods, 3 products</td>
<td>468 cells, 156 + 156 rows</td>
</tr>
</tbody>
</table>
</div><div class="column" style="width:48%;">
<div class="dots">
<ul>
<li><strong>The specification is the deliverable</strong> A unit on every symbol, bounds on every variable. The code is a translation of it.</li>
<li><strong>Four patterns, and nothing else</strong> Index set, balance, capacity, linking. Recognizing the pattern is most of stage 3.</li>
<li><strong>A multiperiod model is its linking constraint</strong> The balance is the only place consecutive periods meet, and a horizon-end condition is mandatory.</li>
<li><strong>Say start or end</strong> Both conventions are valid, and they give different answers.</li>
<li><strong>Split the net position</strong> Two non-negative variables price the two directions differently and stay linear.</li>
<li><strong>Duals are period by period</strong> A capital request names the period, not just the resource.</li>
</ul>
</div>
</div></div>
</section>
<section id="before-we-meet-again" class="slide level2">
<h2>Before we meet again</h2>
<div class="kicker c-amber">
<p>Five things, and reading</p>
</div>
<div class="columns">
<div class="column" style="width:53%;">
<div class="numbered n4">
<ol type="1">
<li><strong>Start HW1</strong>, released today, due Week 4. The linear half needs only today.</li>
<li><strong>Finish the Week 2 notebook</strong> end to end, including Exercises 1 to 3. It reproduces every number quoted today and cross-checks each dual by finite difference.</li>
<li><strong>Complete the workbook</strong> if Activity 2 was not finished, and confirm cell <code>C24</code> reads 42,080.00.</li>
<li><strong>Read the closing note</strong> on the workbook’s <code>Readme</code> sheet.</li>
<li><strong>If Solver failed today</strong>, come to the Week 3 clinic.</li>
</ol>
</div>
</div><div class="column" style="width:45%;">
<div class="cards">
<div class="card c-teal">
<p><strong>Reading</strong></p>
<p>Rao, Ch. 3, on the formulation of linear programs.</p>
<p>Williams, Ch. 3 and 4. Chapter 4 is the single best treatment of the inventory balance in print, with a long discussion of exactly the modeling choices Activity 1 exposed as ambiguities.</p>
<p>Edgar, Himmelblau and Lasdon, Ch. 7, for the process framing.</p>
</div>
</div>
<div class="flag">
<p>Week 3 · 24 August — Networks: transportation, transshipment and process superstructures.</p>
</div>
</div></div>
</section>
<section id="section-2" class="slide level2 dark divider c-amber" data-background-color="#1C242B">
<h2>&nbsp;</h2>
<div class="statement">
<p>The balance equation you wrote<br>around a period today</p>
</div>
<div class="statement-hi">
<p>is written around a node next week,<br>and almost nothing else changes.</p>
</div>
<div class="flag">
<p>Same four patterns. New index set. See you Monday.</p>
</div>
<!-- Shared closing slide. Every week's deck ends with an include of this file
     (see the last line of w01.qmd). One QR serves all fifteen weeks; the
     submission timestamp separates the sessions. -->
</section>
<section id="section-3" class="slide level2 dark mid" data-background-color="#1C242B">
<h2>&nbsp;</h2>
<div class="vcenter">
<div class="columns">
<div class="column" style="width:58%;">
<div class="kicker">
<p>Before you go · 45 seconds</p>
</div>
<h3 id="how-was-today">How was today?</h3>
<div class="lede">
<p>Five questions. Anonymous — no name, no email, no login.</p>
</div>
<div class="flag">
<p>The fourth question is the one I actually use.</p>
</div>
<div class="statement-sub">
<p>The two most common answers open next week’s session.</p>
</div>
<div class="source">
<p>oxidized-challenge-ed9.notion.site</p>
</div>
</div><div class="column" style="width:42%;">
<div class="qr-card">
<p><img data-src="assets/qr_feedback.png" alt="QR code linking to the weekly feedback form"></p>
</div>
<div class="flag center">
<p>Scan now — I will wait</p>
</div>
</div></div>
</div>


</section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="site_libs/revealjs/plugin/search/search.js"></script>
  <script src="site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":false},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: true,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'visible',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'speaker',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'fast',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1280,

        height: 720,

        // Factor of the display size that should remain empty around the content
        margin: 7.5e-2,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    <!-- Click anywhere on a slide to advance.

         Reveal.js has no built-in click-to-advance, so this adds it. Going back is
         the ← key, or the arrow at the left edge of the screen
         (controlsLayout: edges in _quarto.yml).

         It deliberately does nothing when the click means something else: a link or
         control, a double-click, a modified click, the overview (O), a drag that
         selected text, or the click that dismisses a selection. Without those
         guards a student trying to select a sentence would skip a slide instead.

         Note the selection is checked on mousedown, not on click — the browser
         clears the selection before the click event fires. -->
    <script>
    (function () {
      var IGNORE = 'a, button, input, select, textarea, label, summary, video, audio,' +
                   ' iframe, .controls, .slide-menu, .slide-menu-button, .progress,' +
                   ' .speaker-controls, .pdf-page';
      var DRAG_PX = 6;
      var downX = 0, downY = 0, hadSelection = false;

      document.addEventListener('mousedown', function (e) {
        downX = e.clientX;
        downY = e.clientY;
        var s = window.getSelection();
        hadSelection = !!(s && String(s).length > 0);
      }, true);

      function ready(fn) {
        if (typeof Reveal !== 'undefined' && Reveal.isReady && Reveal.isReady()) return fn();
        setTimeout(function () { ready(fn); }, 120);
      }

      ready(function () {
        document.addEventListener('click', function (e) {
          if (e.button !== 0) return;                        // left button only
          if (e.detail > 1) return;                          // ignore double-clicks
          if (e.metaKey || e.ctrlKey || e.altKey || e.shiftKey) return;
          if (e.target.closest && e.target.closest(IGNORE)) return;
          if (Reveal.isOverview() || Reveal.isPaused()) return;
          if (Math.abs(e.clientX - downX) > DRAG_PX ||
              Math.abs(e.clientY - downY) > DRAG_PX) return; // that was a drag
          if (hadSelection) { hadSelection = false; return; } // that click cleared a selection
          Reveal.next();
        }, false);
      });
    })();
    </script>
    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>