// Original teaching questions. Version changes invalidate older saved attempts.
export const VERSION = '2026-10-05.1';
const q = (id, topic, stem, choices, answer, explanation) => ({id, topic, stem, choices: choices.map((text,i)=>({id:String(i),text})), answer:String(answer), explanation});
export const questions = [
q('Q01','Model formulation','A plant must deliver exactly 100 t of a liquid blend today. All purchased feeds A and B enter the product, with no losses or inventory. If xA and xB are purchased tonnes, which requirement represents total mass conservation?', ['xA + xB = 100','xA + xB ≤ 100','xA + xB ≥ 100','0.5xA + 0.5xB = 100'],0,'All purchased mass becomes product, and the required product mass is exactly 100 t. Both underproduction and overproduction violate the stated requirement.'),
q('Q02','Model formulation','A feed contains 2 wt% impurity. The plant consumes x tonnes of that feed per day. Which expression gives the impurity mass entering per day?', ['0.02x tonnes/day','2x tonnes/day','0.02/x tonnes/day','x/0.02 tonnes/day'],0,'2 wt% is a mass fraction of 0.02. Multiplying this fraction by the total feed mass flow gives impurity mass flow.'),
q('Q03','Model formulation','Feeds A and B contain 2 wt% and 10 wt% impurity. Their flows xA and xB are in t/day. Exactly 100 t/day of product may contain at most 5 wt% impurity. Which constraint is correct?', ['0.02xA + 0.10xB ≤ 5','0.02xA + 0.10xB ≤ 0.05','0.02xA + 0.10xB ≥ 5','0.02xA + 0.10xB = 0.05'],0,'The allowable impurity flow is 0.05 × 100 = 5 t/day. A maximum specification is an upper bound, not a required equality.'),
q('Q04','Model formulation','Feed A costs 100 USD/t and feed B costs 60 USD/t. Their flows xA and xB are in t/day. Which objective minimizes daily feed purchase cost?', ['Minimize 100xA + 60xB','Minimize 100/xA + 60/xB','Maximize 100xA + 60xB','Minimize xA + xB'],0,'Unit cost times mass flow has units of USD/day. Minimizing total mass is a different objective and is constant if throughput is fixed.'),
q('Q05','Model interpretation','A blend model has continuous nonnegative feed flows, a linear cost objective, a total mass balance, and linear quality and availability constraints. Which model class applies?', ['Linear program (LP)','Mixed-integer linear program (MILP)','Nonlinear program because flows are continuous','Integer program because the data are whole numbers'],0,'The expressions are linear and all decision variables are continuous. Integer-valued data do not require integer decision variables.'),
q('Q06','Model interpretation','Exactly 100 t/day must be blended. A costs 100 USD/t with 2 wt% impurity and B costs 60 USD/t with 10 wt% impurity. Product impurity is at most 5 wt%. A and B are available up to 100 and 80 t/day. What is the minimum-cost blend?', ['A = 62.5, B = 37.5 t/day','A = 50, B = 50 t/day','A = 20, B = 80 t/day','A = 100, B = 0 t/day'],0,'The mass balance gives A = 100 − B. Quality gives 2 + 0.08B ≤ 5, so B ≤ 37.5. Because B is cheaper, its largest feasible flow is optimal. Daily cost is 8,500 USD.'),
q('Q07','Model verification','A proposed cost-minimization model for a required 100 t/day delivery uses xA + xB ≤ 100 and nonnegative flows. All other constraints allow zero flow, and both unit costs are positive. Which test most directly exposes the demand error?', ['Set xA = xB = 0 and check feasibility','Use a different name for each variable','Increase the solver time limit','Round the reported objective to an integer'],0,'Zero production is feasible in this model and has zero cost, but it fails the required delivery. This is a concrete counterexample to the formulation.'),
q('Q08','Model interpretation','A minimization LP is feasible and has a finite optimum. A maximum impurity limit is relaxed while every other model element stays the same. What must be true about the new optimal objective?', ['It cannot be higher than before','It must be strictly lower','It must be higher','It cannot change'],0,'Relaxing a constraint enlarges or preserves the feasible set. The old optimum remains available, so the new minimum cannot increase. It can stay unchanged.'),
q('Q09','Model interpretation','A feed has an availability constraint x ≤ 80 t/day. At an optimal solution, x = 37.5 t/day. What is the slack in this constraint?', ['42.5 t/day','37.5 t/day','80 t/day','0 t/day'],0,'For an upper-bound constraint, slack equals the bound minus the current value: 80 − 37.5 = 42.5 t/day.'),
q('Q10','MILP logic','Let x ≥ 0 be a purchased quantity and y be binary. M is a valid positive upper bound. What does x ≤ My guarantee?', ['If y = 0, then x = 0','If y = 1, then x > 0','If x = 0, then y = 0','If y = 1, then x = M'],0,'When y = 0, nonnegativity and the upper bound force x = 0. When y = 1, the constraint permits any x between zero and M.'),
q('Q11','MILP logic','An optional supplier must deliver between 20 and 80 t/day when active, and zero when inactive. Let y = 1 mean active. Which constraints correctly express this rule?', ['20y ≤ x ≤ 80y, with y binary','20 ≤ x ≤ 80y, with y binary','x ≤ 80y alone, with y binary','20y ≤ x ≤ 80, with y binary'],0,'For y = 0, both bounds force x = 0. For y = 1, they require 20 ≤ x ≤ 80. The alternatives omit a logical direction or force activation.'),
q('Q12','MILP logic','Supplier B charges 1,200 USD per active day plus 60 USD per tonne. Let xB be t/day and yB be binary activation. Which term represents its total daily cost?', ['60xB + 1,200yB','(60 + 1,200)xB','60xB + 1,200xB yB','60yB + 1,200xB'],0,'The variable purchase cost is 60xB. The fixed daily charge is paid once when yB = 1, so its term is 1,200yB.'),
q('Q13','MILP logic','A supplier can provide at most 80 t/day, but the mass and quality balances imply its flow can never exceed 37.5 t/day. For x ≤ My, which choice is the tightest valid M among these options?', ['37.5 t/day','80 t/day','1,000 t/day','20 t/day'],0,'A valid M must preserve every feasible active flow. The derived upper bound 37.5 is valid and tighter than 80 or 1,000. The bound 20 would incorrectly remove feasible flows.'),
q('Q14','MILP logic','Mass balance and product quality imply B ≤ 37.5 t/day. A supplier contract requires at least 40 t/day whenever B is active. An all-A blend is feasible. What follows?', ['B must be inactive in every feasible solution','The whole model is infeasible','B can be active at 37.5 t/day','B can be active if its fixed fee is reduced'],0,'Activation would require both B ≥ 40 and B ≤ 37.5, which is impossible. Inactivation remains feasible because the all-A blend meets the requirements. Cost changes do not repair this feasibility conflict.'),
q('Q15','Model interpretation','Before its activation fee, the best feasible blend using supplier B costs 8,500 USD/day. The feasible all-A alternative costs 10,000 USD/day. The activation fee does not change the blend constraints. At what fee do the two alternatives have equal total cost?', ['1,500 USD/day','1,200 USD/day','2,500 USD/day','8,500 USD/day'],0,'Set 8,500 + F = 10,000 to obtain F = 1,500 USD/day. Below this fee the best B blend is cheaper. Above it the all-A plan is cheaper.'),
q('Q16','MILP logic','A plant may activate a supplier for the day. Its purchased mass can vary continuously, but activation is a yes/no decision. Which variable domains match these decisions?', ['A nonnegative continuous mass variable and a binary activation variable','Two unrestricted continuous variables','An integer mass variable and an unrestricted activation variable','Two binary variables, one for mass and one for activation'],0,'A mass quantity may take fractional values, so it is continuous and nonnegative. The yes/no activation decision requires a binary variable. These choices describe the decisions without specifying a solution algorithm.'),
q('Q17','Model formulation','At period t, opening inventory is s(t−1), production is x(t), demand is d(t), and closing inventory is s(t). There are no losses, purchases, or backlogs. Which balance is correct?', ['s(t−1) + x(t) = d(t) + s(t)','s(t−1) + d(t) = x(t) + s(t)','x(t) = d(t) for every period','s(t) = s(t−1) + x(t) + d(t)'],0,'Opening inventory and production are the sources of material. Demand and closing inventory are the destinations.'),
q('Q18','Model interpretation','Demand is 40 t in period 1 and 60 t in period 2. Opening inventory is zero, and no backlog or disposal is allowed. If production is 80 t in period 1 and 20 t in period 2, what inventory remains after period 1?', ['40 t','20 t','60 t','80 t'],0,'The period-1 balance is 0 + 80 = 40 + s1, giving s1 = 40 t. In period 2, this inventory plus 20 t of production meets the 60 t demand.'),
q('Q19','Model formulation','A two-period plan has production x1 and x2, costs of 5 and 8 USD/t, and a setup charge of 100 USD for each active period (binary y1 and y2). Inventory s1 carried between periods costs 1 USD/t. Opening and closing inventories are zero. Which objective is correct?', ['Minimize 5x1 + 8x2 + s1 + 100(y1 + y2)','Minimize 5x1 + 8x2 + 100(x1 + x2)','Minimize 5x1 + 8x2 − s1 + 100(y1 + y2)','Minimize 5x1 + 8x2 + s1 + 100'],0,'Production, holding, and per-period setup costs must all be counted. The final term depends on how many periods are active, not on production quantity or a single unconditional charge.'),
q('Q20','Model interpretation','A feasible two-period plan produces 80 t at 5 USD/t and 20 t at 8 USD/t. It carries 40 t between periods at 1 USD/t and pays a 100 USD setup fee in each period. What is its total cost?', ['800 USD','560 USD','700 USD','880 USD'],0,'Production costs 80 × 5 + 20 × 8 = 560 USD. Holding adds 40 USD and the two setups add 200 USD. Total = 800 USD.'),
q('Q21','LLM and verification','An LLM receives a plant description saying only “meet daily demand.” Excess production and storage are not discussed. What is the best next modeling action?', ['Clarify whether demand is an equality or a lower bound and record the decision','Always use an equality without asking','Always allow unlimited excess production','Let the solver decide which inequality the description means'],0,'The wording leaves a material modeling choice unresolved. The modeler should clarify the operating rule or explicitly document an agreed assumption.'),
q('Q22','LLM and verification','An LLM writes a plausible formulation, and a solver reports an optimal solution. Which statement is justified?', ['The encoded model was solved to the reported status, but its match to the physical problem still needs checking','The physical problem must have been formulated correctly','Every omitted operating requirement is automatically enforced','No independent calculation is useful after an optimal status'],0,'A solver evaluates the supplied equations. It cannot establish that those equations faithfully represent requirements that were omitted or mistranslated.'),
q('Q23','LLM and verification','A Pyomo script has just called a solver. Before loading and interpreting the solution, what should it check?', ['The solver termination condition and whether an appropriate solution is available','Only whether variable names are descriptive','Only whether the objective value is positive','Whether the script contains a print statement'],0,'Infeasible, unbounded, interrupted, or failed solves require different handling. A time-limited feasible incumbent also must not be described as a proven optimum.'),
q('Q24','MILP logic','Binary yA and yB indicate whether units A and B operate. Which constraint expresses “B may operate only if A operates”?', ['yB ≤ yA','yA ≤ yB','yA + yB ≤ 1','yA + yB = 1'],0,'If B operates, yB = 1 forces yA = 1. If A operates, B remains optional. The implication does not require B whenever A operates.'),
q('Q25','LLM and verification','A reviewer finds one numerical point that satisfies every constraint in a proposed formulation but violates a stated operating requirement. What can the reviewer conclude?', ['The formulation does not fully represent the stated requirements','The model is correct if that point is not optimal','The solver must contain a numerical error','A second LLM agreeing with the formulation would resolve the issue'],0,'One valid counterexample disproves equivalence between the mathematical feasible set and the stated requirements. A correct formulation must exclude forbidden feasible points, even when they are not optimal.')
];
