#!/usr/bin/env python3
"""
Turn returned member forms into website data — for the ONE-FILE people model.

The loop this is built for
--------------------------
1. Send current members `member_form.docx`.
2. They send back the filled form plus one photo.
3. Drop every file you get into `inbox/` — forms and photos together, any names.
4. Run this. It crops the photos, then MERGES the form people into
   `_data/people.yml` as current members and rewrites the file.
5. Read the YAML, fix anything odd, commit.

    pip install python-docx pyyaml pillow
    python tools/make_people.py

What it does NOT do
-------------------
It never deletes alumni. Every entry already in `_data/people.yml` is kept.
A form only adds a new current member, or updates the current-member fields
(role, year, research sentence, photo, link) of someone already listed —
their alumni history (phd, thesis, postdoc, now) is left untouched. So a
former PhD student who rejoins as a postdoc keeps both stories on one entry.

It also never invents a value: a field left blank in the form is left out.
The file's comments and section headers are regenerated every run, so the
YAML always comes out grouped and documented the same way.

Schema written (see the header block at the top of the generated file)
----------------------------------------------------------------------
    name · status · role · since · topic         (current members)
    phd · thesis · postdoc · now                 (alumni — hand-entered)
    photo · link                                 (shared, optional)

Photos: phone photos arrive at 3000 px in every aspect ratio. Each is cropped
to a square biased toward the upper third (where faces sit) and saved at 600 px.
The site renders them grayscale until hover, which makes a set of mismatched
phone snaps still look like one group.
"""
import re, sys, unicodedata, pathlib, difflib
import yaml
from docx import Document
from PIL import Image, ImageOps

ROOT = pathlib.Path(__file__).resolve().parent.parent
INBOX = ROOT / "inbox"
OUT_PHOTOS = ROOT / "img" / "people"
OUT_YAML = ROOT / "_data" / "people.yml"
PHOTO_PX = 600

# form label  ->  yaml key. Matching is fuzzy, so a member who retypes
# "Full Name" or adds a colon still parses. The form still asks for a short
# name and previous degree; the current site does not render them, so they
# are parsed but not written. Add them back to KEY_ORDER if you want them.
FIELDS = {
    "full name": "name",
    "role": "role",
    "year joined": "since",
    "research, in one sentence": "topic",
    "orcid or google scholar": "link",
}
# The full order an entry is written in. Only keys that are present appear.
KEY_ORDER = ["name", "status", "level", "role", "since", "topic",
             "deng", "meng", "thesis", "postdoc", "now", "photo", "link"]

HINT = re.compile(r"^(exactly as|optional|phd student /|e\.g\.|max 20 words)", re.I)

HEADER = """\
# ─────────────────────────────────────────────────────────────────────────────
# EVERYONE in the group — current and alumni — lives in this ONE file.
# One entry per person. The People page has two blocks, CURRENT and ALUMNI,
# each split into three levels: Postdoc, Doctoral (D.Eng.), Master's (M.Eng.).
#
#   status: current + level: postdoc → Current · Postdoctoral researchers
#   status: current + level: deng    → Current · Doctoral students (D.Eng.)
#   status: current + level: meng    → Current · Master's students (M.Eng.)
#
#   postdoc: <period>  → Alumni · Postdoctoral researchers
#   deng: <year>       → Alumni · Doctoral graduates (D.Eng.)
#   meng: <year>       → Alumni · Master's graduates (M.Eng.)
#
# Current members are placed by `level`; alumni by their degree/stint markers
# (deng / meng / postdoc). A person can carry more than one marker and appear in
# more than one alumni group from a single entry. You never edit HTML.
#
# A sub-group with nobody in it simply does not appear.
#
# This file is regenerated by tools/make_people.py when new member forms come
# in, but the script only adds/updates current members; it never removes
# alumni. Hand-editing between runs is fine.
#
# ── Fields ───────────────────────────────────────────────────────────────────
#   name     required. No "Dr." — the role line shows the level.
#   status   current | alumnus | example   (example never displays)
#   level    current members only: postdoc | deng | meng  (which current group)
#   role     current members only: free text, e.g. "Doctoral student"
#   since    current members only: year they joined
#   topic    current members only: one sentence, plain English, no acronyms
#   deng     year a Doctoral degree (D.Eng.) was earned here → Doctoral graduates
#   meng     year a Master's degree (M.Eng.) was earned here → Master's graduates
#   thesis   thesis title (HTML like Na<sub>0.44</sub>MnO<sub>2</sub> is fine)
#   postdoc  postdoc period here, e.g. "2022–2026" → Postdoctoral alumni
#   now      where they are now. OMIT if still at Chulalongkorn.
#   photo    square JPEG in img/people/. Omit → a placeholder shows.
#   link     ORCID / Google Scholar URL. Optional.
# ─────────────────────────────────────────────────────────────────────────────
"""

CURRENT_HDR = "\n# ── Current members (postdocs, D.Eng. and M.Eng. students) ───────────────────\n"
CURRENT_EMPTY = "# (No current members listed yet — they are added here as forms come in.)\n"
ALUMNI_HDR = "\n# ── Alumni (postdocs, D.Eng. and M.Eng. graduates) ───────────────────────────\n"

EXAMPLE_BLOCK = """
# ── Template (never displayed; copy this block to add a person) ───────────────
- name: Example Person
  status: example
  level: deng                                        # postdoc | deng | meng (current only)
  role: Doctoral student
  since: 2024
  topic: One sentence, plain English, no acronyms.
  deng:                                              # year, if D.Eng. earned here
  meng:                                              # year, if M.Eng. earned here
  thesis:                                            # thesis title
  postdoc:                                           # "2026–2028", if a postdoc here
  now:                                               # omit if still at Chulalongkorn
  photo: example-person.jpg                          # square JPEG in img/people/
  link: https://orcid.org/0000-0000-0000-0000
"""

# Map the form's free-text Role to a controlled `level` for current-member grouping.
def role_to_level(role):
    r = (role or "").lower()
    if "postdoc" in r or "post-doc" in r or "postdoctoral" in r:
        return "postdoc"
    if "master" in r or "m.eng" in r or "meng" in r or "msc" in r or "m.sc" in r:
        return "meng"
    if "phd" in r or "ph.d" in r or "doctora" in r or "d.eng" in r or "deng" in r:
        return "deng"
    return None


def slugify(name):
    s = unicodedata.normalize("NFKD", name).encode("ascii", "ignore").decode()
    s = re.sub(r"[^a-zA-Z0-9]+", "-", s).strip("-").lower()
    return "-".join(s.split("-")[:2]) or "member"


def norm(name):
    return " ".join((name or "").split()).lower()


def clean(v):
    v = " ".join(v.split())
    if not v or HINT.match(v):        # they left the grey hint text in place
        return ""
    return v


def read_form(path):
    doc = Document(path)
    if not doc.tables:
        print(f"  !! {path.name}: no table found — is this the right form?")
        return None
    rec = {}
    for row in doc.tables[0].rows:
        label = " ".join(row.cells[0].text.split("\n")[0].split()).strip(" :*").lower()
        key = FIELDS.get(label)
        if key is None:                       # fuzzy fallback
            m = difflib.get_close_matches(label, FIELDS, n=1, cutoff=0.75)
            key = FIELDS[m[0]] if m else None
        if key is None:
            continue
        val = clean(row.cells[1].text)
        if val:
            rec[key] = val
    if not rec.get("name"):
        print(f"  !! {path.name}: no name filled in — skipped")
        return None
    if rec.get("since"):
        m = re.search(r"(20\d\d)", rec["since"])
        rec["since"] = int(m.group(1)) if m else rec.pop("since", None)
    rec["status"] = "current"                 # anyone returning a form is current
    lvl = role_to_level(rec.get("role"))
    if lvl:
        rec["level"] = lvl
    return rec


def square(src, dest):
    im = Image.open(src)
    im = ImageOps.exif_transpose(im).convert("RGB")   # phones lie about rotation
    w, h = im.size
    side = min(w, h)
    left = (w - side) // 2
    top = int((h - side) * 0.25)                      # bias up: faces are not centred
    im = im.crop((left, top, left + side, top + side)).resize((PHOTO_PX, PHOTO_PX), Image.LANCZOS)
    im.save(dest, "JPEG", quality=86, optimize=True, progressive=True)


def load_existing():
    """Every entry already in the file, minus the example template."""
    if not OUT_YAML.exists():
        return []
    data = yaml.safe_load(OUT_YAML.read_text(encoding="utf-8")) or []
    if not isinstance(data, list):
        return []
    return [p for p in data if isinstance(p, dict) and (p.get("status") != "example")]


def dump_entry(p):
    d = {k: p[k] for k in KEY_ORDER if k in p and p[k] not in (None, "")}
    return yaml.dump([d], allow_unicode=True, sort_keys=False, width=100)


def render(people):
    """Rebuild the whole file: header, current members, alumni, template."""
    current = [p for p in people if p.get("status") == "current"]
    alumni = [p for p in people if p.get("status") != "current"]
    out = [HEADER, CURRENT_HDR]
    out.append("".join(dump_entry(p) for p in current) if current else CURRENT_EMPTY)
    if alumni:
        out.append(ALUMNI_HDR)
        out.append("".join(dump_entry(p) for p in alumni))
    out.append(EXAMPLE_BLOCK)
    return "".join(out)


def main():
    if not INBOX.exists():
        INBOX.mkdir()
        print(f"Created {INBOX.relative_to(ROOT)}/ — put the returned forms and photos in it, then run again.")
        return
    forms = sorted(p for p in INBOX.iterdir() if p.suffix.lower() == ".docx" and not p.name.startswith("~$"))
    photos = [p for p in INBOX.iterdir() if p.suffix.lower() in {".jpg", ".jpeg", ".png", ".heic", ".webp"}]
    if not forms:
        print(f"No .docx forms in {INBOX.relative_to(ROOT)}/")
        return
    OUT_PHOTOS.mkdir(parents=True, exist_ok=True)

    people = load_existing()
    index = {norm(p["name"]): p for p in people if p.get("name")}
    used = set()
    print(f"{len(forms)} forms, {len(photos)} photos, {len(people)} people already on file\n")

    for f in forms:
        rec = read_form(f)
        if not rec:
            continue
        slug = slugify(rec["name"])

        # match a photo: by form filename, then by the person's name
        keys = [f.stem.lower()] + [w.lower() for w in re.split(r"[\s,]+", rec["name"]) if len(w) > 2]
        hit = next((p for p in photos if p not in used
                    and any(k in p.stem.lower() or p.stem.lower() in k for k in keys)), None)
        if hit:
            used.add(hit)
            dest = OUT_PHOTOS / f"{slug}.jpg"
            try:
                square(hit, dest)
                rec["photo"] = dest.name
                note = f"photo {hit.name}"
            except Exception as e:
                note = f"PHOTO FAILED ({e}) — convert it to JPEG by hand"
        else:
            note = "no photo matched — a placeholder will show"

        if not rec.get("level"):
            note = "NO LEVEL from role — set level: postdoc|deng|meng by hand. " + note

        existing = index.get(norm(rec["name"]))
        if existing:
            existing.update(rec)              # refresh current-member fields; keep degree markers
            action = "updated"
        else:
            people.append(rec)
            index[norm(rec["name"])] = rec
            action = "added"
        print(f"  {action:<8} {rec['name']:<32} {rec.get('role','?'):<18} {note}")

    orphan = [p.name for p in photos if p not in used]
    if orphan:
        print("\n  photos with no form:", ", ".join(orphan))

    body = render(people)
    if OUT_YAML.exists() and OUT_YAML.read_text(encoding="utf-8") != body:
        print(f"\n{OUT_YAML.relative_to(ROOT)} would change:")
        old = OUT_YAML.read_text(encoding="utf-8").splitlines()
        for line in list(difflib.unified_diff(old, body.splitlines(), "current", "new", lineterm=""))[:60]:
            print("   ", line)
        if input("\nWrite it? [y/N] ").strip().lower() != "y":
            print("Nothing written.")
            return
    OUT_YAML.write_text(body, encoding="utf-8")
    n_current = sum(1 for p in people if p.get("status") == "current")
    print(f"\nWrote {OUT_YAML.relative_to(ROOT)} — {len(people)} people ({n_current} current) "
          f"and photos in {OUT_PHOTOS.relative_to(ROOT)}/")
    print("Read the YAML before committing. Anything blank in a form is simply absent — that is intended.")


if __name__ == "__main__":
    main()
